### ISSUE TITLE
Wrong date&time in Allure report

### ISSUE THREAD

**Issue by LedAlex** [jenkinsci/allure-plugin#100]
### Context
- **Jenkins version**: 2.22
- **Job type**: Freestyle

- **Allure plugin version**: 2.10-2.14

### Problem description

Allure shows wrong date&time in report generated via Allure Jenkins Plugin 2.10-2.14.

### Logs & Traces

![2017-04-11 0000](https://cloud.githubusercontent.com/assets/27248144/24895308/60325226-1e98-11e7-9189-706b0730321a.png)
![2017-04-11 0001](https://cloud.githubusercontent.com/assets/27248144/24895312/63f39596-1e98-11e7-8eb9-b10166dd6d2a.png)

[testrun.json.txt](https://github.com/jenkinsci/allure-plugin/files/912295/testrun.json.txt)
[d99d0664-9e4c-467c-83bf-bc665d9eda8a-testsuite.xml.txt](https://github.com/jenkinsci/allure-plugin/files/912296/d99d0664-9e4c-467c-83bf-bc665d9eda8a-testsuite.xml.txt)

**Server configuration**:
/etc$ env
XDG_SESSION_ID=528
HOSTNAME=os-2330.homecredit.ru
SHELL=/bin/bash
HISTSIZE=1000
SSH_CLIENT=10.6.33.124 65363 22
USER=aledyaev
MAIL=/var/spool/mail/aledyaev
PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/aledyaev/.local/bin:/home/aledyaev/bin
PWD=/etc
HISTCONTROL=ignoredups
SHLVL=1
HOME=/home/aledyaev
LOGNAME=aledyaev
SSH_CONNECTION=10.6.33.124 65363 10.5.10.154 22
LESSOPEN=||/usr/bin/lesspipe.sh %s
XDG_RUNTIME_DIR=/run/user/1028
_=/usr/bin/env
OLDPWD=/var/lib/jenkins/jobs/at_smoke_homer/jobs/old_smoke/jobs

/etc$ locale
LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=

/etc$ date
Tue Apr 11 09:32:19 MSK 2017

**Clients are in UTC+3 timezone.**

**Comment by LedAlex** [comment]
Is there any information availliable when this bug wil be fixed?

**Comment by eroshenkoam** [comment]
@LedAlex Can you update plugin to the latest version (2.23)?
I fixed many issues from 2.14
