### ISSUE TITLE
It is possible to set allure-report directory in the plugin?

### ISSUE THREAD

**Issue by netmajor** [jenkinsci/allure-plugin#106]
It is possible to set allure-report directory in the plugin like in allure cli ?
allure generate directory-with-results/ -o directory-with-report

**Comment by eroshenkoam** [comment]
It's no possible now :( But I can make it in the next release.
Can you provide a more detailed explanation why would you need this.

**Comment by netmajor** [comment]
Now we can only set path for allure-results in jenkins plugin and allure-report is generated by default in root directory. But we want to place both in specific folder in our project and not spoil root.

**Comment by elhe** [comment]
I will be happy to have this ability too. It's useful when  you have parallel test runs in one pipeline and don't want to mix results

**Comment by satyasreem** [comment]
@eroshenkoam This is exactly what I am looking for as well.
How do I make use of this  change to override the default allure-report directory.
I am trying this:
`allure([
                            includeProperties: true,
                            jdk: '',
                            properties: [[key: 'allure.results.directory', value:'reports-firefox']],
                            reportBuildPolicy: 'ALWAYS',
                            results: [[path: 'reports-firefox']]
                    ])`

But I see the command line still uses:
`-c -o /datadisk/jenkins/workspace/mp_web_webdriver/allure-report
`

Please provide any import on this?
