### ISSUE TITLE
Add ability to not delete report folder on slave

### ISSUE THREAD

**Issue by LawYard** [jenkinsci/allure-plugin#114]
Hi!

Folder with allure report deletes after artifact building in current plugin version. We have some troubles here with that logic, cause we want to upload report to Amazon S3 and use its `Website Hosting`. For using this S3 feature we need to upload **unzipped** folder, not zip.

So, can u add some features:

- Ability to save artifact copy somewhere in build workspace
- Ability to set `Dont delete report folder`

**Comment by LawYard** [comment]
Up @eroshenkoam

**Comment by vbragin** [comment]
See the linked issue.
