### ISSUE TITLE
Duplicated report links in pipeline jobs

### ISSUE THREAD

**Issue by i-feofilaktov** [jenkinsci/allure-plugin#115]
### Context
- **Jenkins version**: 2.46.2
- **Job type**: Pipeline

- **Allure plugin version**: 2.15
- **Allure commandline version**: 1.5.2

### Problem description
If pipeline generates several reports, several links appear at job's main page (screenshot). ![duplicated_report_links](https://cloud.githubusercontent.com/assets/14952033/26206346/40cea232-3bed-11e7-9a8b-6c86585a0c80.png)

All these links lead to similar report

Pipeline script provides ability to restart stage in case of failure, so useful scenario is the following:
test stage fails due to some unstable problems, user checks out the report and decides to restart stage,  second try is successful and pipeline script is able to move on.

### Logs & Traces
Set up:
```
root@75a909fd16de:/# apt-get -y install \
    python \
    python-pip \
    libxml2-dev \
    libxslt1-dev \
    python-dev \
    zlib1g-dev
root@75a909fd16de:/# pip install pytest
root@75a909fd16de:/# pip install pytest-allure-adaptor
root@75a909fd16de:/# echo "def test_smth(): pass" > test_allure.py
root@75a909fd16de:/# echo "def test_smth(): assert 0 == 1" > test_allure_negative.py
```

Pipeline script:
```
node('master') {
    stage ('Run tests') {
        sh 'py.test /test_allure.py --alluredir /tmp/allure-results'
        allure([includeProperties: false, jdk: 'Java', properties: [], reportBuildPolicy: 'ALWAYS', results: [[path: '/tmp/allure-results']]])
    }
    stage ('Run tests again') {
        try {
            sh 'py.test /test_allure_negative.py --alluredir /tmp/allure-results-negative'
        } catch (e) {
            allure([includeProperties: false, jdk: 'Java', properties: [], reportBuildPolicy: 'ALWAYS', results: [[path: '/tmp/allure-results-negative'], [path: '/tmp/allure-results']]])
        }
    }
    stage ('Cleanup') {
        sh 'rm -rf /tmp/allure-results'
        sh 'rm -rf /tmp/allure-results-negative'
    }
}
```

**Comment by vblg** [comment]
Have the same issue

**Comment by undron** [comment]
Duplicate not only in pipeline, but freestyle jobs 
![2017-08-02_14-12-56](https://user-images.githubusercontent.com/1076685/28871663-4cb8ea1c-778e-11e7-9056-75164bcc717e.png)

**Comment by nvs4a3** [comment]
Is this issue resolved? If so, in which release of plugin? I am still seeing Duplicate links Issue..

**Comment by nvs4a3** [comment]
> Duplicate not only in pipeline, but freestyle jobs
> ![2017-08-02_14-12-56](https://user-images.githubusercontent.com/1076685/28871663-4cb8ea1c-778e-11e7-9056-75164bcc717e.png) 
Is the above Issue resolved?

**Comment by nvs4a3** [comment]
> ## Issue
> ### Context
> * **Jenkins version**: 2.46.2
> * **Job type**: Pipeline
> * **Allure plugin version**: 2.15
> * **Allure commandline version**: 1.5.2
> 
> ### Problem description
> If pipeline generates several reports, several links appear at job's main page (screenshot). ![duplicated_report_links](https://cloud.githubusercontent.com/assets/14952033/26206346/40cea232-3bed-11e7-9a8b-6c86585a0c80.png)
> 
> All these links lead to similar report
> 
> Pipeline script provides ability to restart stage in case of failure, so useful scenario is the following:
> test stage fails due to some unstable problems, user checks out the report and decides to restart stage, second try is successful and pipeline script is able to move on.
> 
> ### Logs & Traces
> Set up:
> 
> ```
> root@75a909fd16de:/# apt-get -y install \
>     python \
>     python-pip \
>     libxml2-dev \
>     libxslt1-dev \
>     python-dev \
>     zlib1g-dev
> root@75a909fd16de:/# pip install pytest
> root@75a909fd16de:/# pip install pytest-allure-adaptor
> root@75a909fd16de:/# echo "def test_smth(): pass" > test_allure.py
> root@75a909fd16de:/# echo "def test_smth(): assert 0 == 1" > test_allure_negative.py
> ```
> 
> Pipeline script:
> 
> ```
> node('master') {
>     stage ('Run tests') {
>         sh 'py.test /test_allure.py --alluredir /tmp/allure-results'
>         allure([includeProperties: false, jdk: 'Java', properties: [], reportBuildPolicy: 'ALWAYS', results: [[path: '/tmp/allure-results']]])
>     }
>     stage ('Run tests again') {
>         try {
>             sh 'py.test /test_allure_negative.py --alluredir /tmp/allure-results-negative'
>         } catch (e) {
>             allure([includeProperties: false, jdk: 'Java', properties: [], reportBuildPolicy: 'ALWAYS', results: [[path: '/tmp/allure-results-negative'], [path: '/tmp/allure-results']]])
>         }
>     }
>     stage ('Cleanup') {
>         sh 'rm -rf /tmp/allure-results'
>         sh 'rm -rf /tmp/allure-results-negative'
>     }
> }
> ```

Is the above Issue resolved?

**Comment by teegalasv** [comment]
Hi am having the same issue.. Is this fixed? if yes, Can some tell how to fix it??

**Comment by nvs4a3** [comment]
> Hi am having the same issue.. Is this fixed? if yes, Can some one tell how to fix it??

Any luck with the above Issue?

**Comment by nvs4a3** [comment]
> Duplicate not only in pipeline, but freestyle jobs
> ![2017-08-02_14-12-56](https://user-images.githubusercontent.com/1076685/28871663-4cb8ea1c-778e-11e7-9056-75164bcc717e.png)

Hi  @undron  @i-feofilaktov  Is the above Issue resolved for you? If yes, how was the Issue fixed? Any new version fixed the Issue?

**Comment by puneetpunj** [comment]
Any update on the fix?

**Comment by VaclavKlic** [comment]
Was someone able to solve this?

**Comment by stszap** [comment]
Having the same problem on 2.30.3 with the same use-case as the OP. If `allure()` is run twice in the same job run then 2 icons appear near that build in the history and both have the same URL but only the second report is accessible. The first one is just shown in the trend graph but you can't open and inspect it. 

You can see on the screenshot that the second try failed for builds 2 and 4 but when you click on a  part of the graph with an error "bump" it just shows you the second report without errors.
![Screen Shot 2022-11-17 at 4 59 34 PM](https://user-images.githubusercontent.com/20905199/202454236-8e12db2d-6fcd-4b85-99ad-d8554729a5c7.png)
