### ISSUE TITLE
plugin can't be upgraded to ver. 2.16 

### ISSUE THREAD

**Issue by emaks** [jenkinsci/allure-plugin#121]
### Context
- **Jenkins version**:  2.63
- **Allure plugin version**: 2.15-SNAPSHOT (private-05/30/2017 19:15-jenkins)

### Problem description
- open /pluginManager
- select allure plugin for upgrade 
![allure](https://cloud.githubusercontent.com/assets/1282000/26635209/b9a4b596-4621-11e7-93af-eba26c0a1bb0.png)
- click "Download now and install after restart" button

plugin has not been upgraded to ver. 2.16

**Comment by eroshenkoam** [comment]
plugin update to 2.16, but MANIFEST version is incorrect. 
will be fixes today in next release 2.17

**Comment by eroshenkoam** [comment]
fixed in 2.17, enjoy
