### ISSUE TITLE
Add plugin support to Jenkins Job Builder

### ISSUE THREAD

**Issue by tortila** [jenkinsci/allure-plugin#123]
## Issue
This is a feature request. I saw on [your website](http://wiki.qatools.ru/display/AL/Allure+Jenkins+Plugin) that you support Jenkins DSL. I'd like to request adding a support for a similar tool called [Jenkins Job Builder](https://docs.openstack.org/infra/jenkins-job-builder/). 
### Context
Jenkins Job Builder is a popular tool developed by OpenStack. Jobs definitions are in yaml config files, which also support raw xml snippets. Currently it is possible to have Allure Plugin working with injected xml, e.g.:
```yaml
  publishers
    - raw:
        xml: |
          <ru.yandex.qatools.allure.jenkins.AllureReportPublisher plugin="allure-jenkins-plugin@2.15-SNAPSHOT">
          <config>
          <jdk />
          <properties class="empty-list" />
          <results>
          <ru.yandex.qatools.allure.jenkins.config.ResultsConfig>
          <path>log/allure-results</path>
          </ru.yandex.qatools.allure.jenkins.config.ResultsConfig>
          </results>
          <reportBuildPolicy>ALWAYS</reportBuildPolicy>
          <includeProperties>false</includeProperties>
          </config>
          </ru.yandex.qatools.allure.jenkins.AllureReportPublisher>
```
It would be easier to use if there was a native support for this plugin and the config would look like:
```yaml
publishers
  - allure:
      results-path: 'selenium/log/allure-results'
      report-build-policy: ALWAYS
      include-properties: false
```
See documentation for [other publisher plugins](https://docs.openstack.org/infra/jenkins-job-builder/publishers.html) for reference.

**Comment by ehborisov** [comment]
@tortila I've made a contribution to Jenkins Job Builder. https://review.openstack.org/#/c/475185/
it should be merged in one of the upcoming releases.
