### ISSUE TITLE
Can't find allure commandline in a matrix style job

### ISSUE THREAD

**Issue by danalbu** [jenkinsci/allure-plugin#139]
I get this error when i run allure in a matrix style job and the tests fail.
**LOG SUB-JOB**

ERROR: Step ‘Allure Report’ aborted due to exception: 
09:56:54 java.io.IOException: Can't find allure commandline <null>
09:56:54 	at ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation$2.call(AllureCommandlineInstallation.java:63)
09:56:54 	at ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation$2.call(AllureCommandlineInstallation.java:58)
09:56:54 	at hudson.remoting.UserRequest.perform(UserRequest.java:121)
09:56:54 	at hudson.remoting.UserRequest.perform(UserRequest.java:49)
09:56:54 	at hudson.remoting.Request$2.run(Request.java:326)
09:56:54 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
09:56:54 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
09:56:54 	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
09:56:54 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
09:56:54 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
09:56:54 	at hudson.remoting.Engine$1$1.run(Engine.java:69)
09:56:54 	at java.lang.Thread.run(Thread.java:722)
09:56:54 	at ......remote call to Channel to /16.60.153.0(Native Method)
09:56:54 	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1545)
09:56:54 	at hudson.remoting.UserResponse.retrieve(UserRequest.java:253)
09:56:54 	at hudson.remoting.Channel.call(Channel.java:830)
09:56:54 	at ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation.getMajorVersion(AllureCommandlineInstallation.java:58)
09:56:54 	at ru.yandex.qatools.allure.jenkins.ReportBuilder.build(ReportBuilder.java:43)
09:56:54 	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:258)
09:56:54 	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:181)
09:56:54 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
09:56:54 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
09:56:54 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
09:56:54 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
09:56:54 	at hudson.model.Build$BuildExecution.post2(Build.java:186)
09:56:54 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
09:56:54 	at hudson.model.Run.execute(Run.java:1753)
09:56:54 	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
09:56:54 	at hudson.model.ResourceController.execute(ResourceController.java:98)
09:56:54 	at hudson.model.Executor.run(Executor.java:405)
09:56:54 Finished: FAILURE

**LOG MATRIX JOB PARRENT**
FATAL: Can't find allure commandline <null>
09:56:55 java.io.IOException: Can't find allure commandline <null>
09:56:55 	at ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation$2.call(AllureCommandlineInstallation.java:63)
09:56:55 	at ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation$2.call(AllureCommandlineInstallation.java:58)
09:56:55 	at hudson.remoting.UserRequest.perform(UserRequest.java:121)
09:56:55 	at hudson.remoting.UserRequest.perform(UserRequest.java:49)
09:56:55 	at hudson.remoting.Request$2.run(Request.java:326)
09:56:55 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
09:56:55 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
09:56:55 	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
09:56:55 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
09:56:55 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
09:56:55 	at hudson.remoting.Engine$1$1.run(Engine.java:69)
09:56:55 	at java.lang.Thread.run(Thread.java:722)
09:56:55 	at ......remote call to Channel to /16.60.153.1(Native Method)
09:56:55 	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1545)
09:56:55 	at hudson.remoting.UserResponse.retrieve(UserRequest.java:253)
09:56:55 	at hudson.remoting.Channel.call(Channel.java:830)
09:56:55 	at ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation.getMajorVersion(AllureCommandlineInstallation.java:58)
09:56:55 	at ru.yandex.qatools.allure.jenkins.ReportBuilder.build(ReportBuilder.java:43)
09:56:55 	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:258)
09:56:55 	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.access$000(AllureReportPublisher.java:56)
09:56:55 	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher$1.endBuild(AllureReportPublisher.java:229)
09:56:55 	at hudson.matrix.MatrixBuild$MatrixBuildExecution.post2(MatrixBuild.java:422)
09:56:55 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
09:56:55 	at hudson.model.Run.execute(Run.java:1753)
09:56:55 	at hudson.matrix.MatrixBuild.run(MatrixBuild.java:313)
09:56:55 	at hudson.model.ResourceController.execute(ResourceController.java:98)
09:56:55 	at hudson.model.Executor.run(Executor.java:405)

The allure report generates in the children jobs but does not get aggregated to the main job.
**Jenkins OS: **WINDOWS**
Jenkins : 2.46.3
Allure: 1.5.0
Allure Jenkins Plugin: 2.19
Allure cli is installed automatically from central.**

**Comment by vbragin** [comment]
@danalbu Try to update plugin to latest version and try again.
Why don't you use Allure 2 to generate the report?
Please write you result here.

**Comment by eroshenkoam** [comment]
Closed due inactivity, please feel free to reopen this issue
