### ISSUE TITLE
allure-report folder doesn't exist in workspace

### ISSUE THREAD

**Issue by Metaun** [jenkinsci/allure-plugin#148]
### Context
- **Jenkins version**: 2.60.1
- **Job type**: Freestyle

- **Allure plugin version**: 2.20
- **Allure commandline version**: 2.3

### Problem description

I'm trying to create HTML Publisher report with allure , but can't find HTML directory to archive for allure-report folder. 
![selection_026](https://user-images.githubusercontent.com/10543214/28836756-eef1e3a2-76f2-11e7-8e2b-134d8515f2cc.png)

When I run job it shows : 
```
...
Report successfully generated to /opt/jenkins/workspace/ui-tests/allure-report
Allure report was successfully generated.
Creating artifact for the build.
Artifact was added to the build.
[htmlpublisher] Archiving at PROJECT level /opt/jenkins/workspace/ui-tests/allure-report to /var/jenkins_home/jobs/kameleoon-ui-tests/htmlreports/HTML_Report
ERROR: Specified HTML directory '/opt/jenkins/workspace/ui-tests/allure-report' does not exist.
```

**Comment by eroshenkoam** [comment]
@Metaun allure published automatically, you don't need to use Html Publisher

**Comment by Metaun** [comment]
@eroshenkoam oh.. I got it. 
But anyway can I get an access to allure-report folder from Jenkins job ?

**Comment by gavrilfb** [comment]
@Metaun It's no longer exist, automatically deleted when the artifact was created.
Workaround for that is probably to access the artifact and extract it.
At least that's how I'm doing it.

**Comment by vbragin** [comment]
#106

**Comment by vbragin** [comment]
See the linked issue.

**Comment by pitzqa** [comment]
Hello Guys,
My "allure-results" generates as NaN%

Here is Jenkins O/P; (I am working on Protractor+Jenkins and Try to generate a report using allure)

..........................
[Jenkins_ProjectName] $ /var/lib/jenkins/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/allure-reports/bin/allure generate -c -o /var/lib/jenkins/workspace/Jenkins_ProjectName/allure-results
allure-results does not exists
Report successfully generated to /var/lib/jenkins/workspace/Jenkins_ProjectName/allure-results
Allure report was successfully generated.
Creating artifact for the build.
Artifact was added to the build.
Finished: FAILURE


![allure-results](https://user-images.githubusercontent.com/39620464/41725348-29f25718-758d-11e8-9aa7-2e63fe85619d.png)

**Comment by pitzqa** [comment]
Hello Guys,
My "allure-results" generates as NaN%

Here is Jenkins O/P; (I am working on Protractor+Jenkins and Try to generate a report using allure)

..........................
[Jenkins_ProjectName] $ /var/lib/jenkins/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/allure-reports/bin/allure generate -c -o /var/lib/jenkins/workspace/Jenkins_ProjectName/allure-results
allure-results does not exists
Report successfully generated to /var/lib/jenkins/workspace/Jenkins_ProjectName/allure-results
Allure report was successfully generated.
Creating artifact for the build.
Artifact was added to the build.
Finished: FAILURE

![allure-results](https://user-images.githubusercontent.com/39620464/41725694-15e784fe-758e-11e8-998e-5ec1b419413f.png)

**Comment by morinted** [comment]
For anyone looking to read files like `summary.json` or other artifacts generated by the allure plugin, I followed @gavrilfb's advice in finding the generated `allure-results.zip` which I found using:

```
"$JENKINS_HOME/jobs/$JOB_NAME/builds/$BUILD_NUMBER/archive/allure-report.zip"
```

You can then unzip it and access build history, summary info, etc.
