### ISSUE TITLE
Add ability for set output dir with site content

### ISSUE THREAD

**Issue by admizh** [jenkinsci/allure-plugin#15]
After test phase, i invoke  generate report step, and allure generate temp directory in jenkins workspace dir - with site content. After them site directory has cloned to build directory, but temp directory not cleaned. Currently i have alot of temp dirs in my workspace.
![image](https://cloud.githubusercontent.com/assets/6014483/9071302/a863f680-3b05-11e5-860d-a34eac0c27ab.png)
Pls add ability for set output dir with site content

**Comment by eroshenkoam** [comment]
fixed in 2.8
