### ISSUE TITLE
Empty report when using a Jenkins pipeline step

### ISSUE THREAD

**Issue by shat00n** [jenkinsci/allure-plugin#156]
## Issue
I'm getting an empty report attached to Jenkins after switching to a pipeline job.
It seems that command skips/don't see a parameter of tests results placeholder

### Context
- **Jenkins version**: 2.60.2
- **Job type**: Pipeline

- **Allure plugin version**: 2.22
- **Allure commandline version**: 2.3.1

### Problem description
- Generate report using results in CI/allure_reports dir:
allure jdk: '', results: [[path: "CI/allure_reports"]]
- what was expected
To see in the logs anything like this:

> /tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/2.3.1/bin/allure generate CI/allure_reports -o allure-report
> Report successfully generated to allure-report
> 
And to get a report with rest results published in Jenkins 
- what occurred finally

> /tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/2.3.1/bin/allure generate -o allure-report
> allure-results does not exists
> send analytics
> Report successfully generated to CI/allure-report

Empty report has been generated under "CI/allure_reports/allure-report" and published on Jenkins

### Notes
- The step command was generated using a snippet generator
- Using the same paths exactly but with a free style job and a regular plugin works properly
- Its a new config, so don't know if its worked on older versions

Thanks

**Comment by shat00n** [comment]
setup issue

**Comment by jeitae** [comment]
someone can help?

**Comment by eroshenkoam** [comment]
@jeitae You have the same issue?

**Comment by jeitae** [comment]
yes, so... what kind of test are you do?

**Comment by jeitae** [comment]
i mean, i resolved my problem yesterday (made a java with maven and testng project) only change pom.xml and reports routes on jenkins (only pom.xml and target/allure-reports configure), later copy all my project files into /var/lib/jenkins/workspace/TESTDIRNAME change own and permissions to jenkins user and problem ready, we need target dir into jenkins workspace

On project pom file change pom.xml target:
![image](https://user-images.githubusercontent.com/8714477/29990584-3a33aa40-8f39-11e7-8593-5d61fb5f5246.png)

On Allure reports change to target/allure-reports:
![image](https://user-images.githubusercontent.com/8714477/29990592-4a588418-8f39-11e7-8c8f-b25174dc7020.png)

Into workspace (Desarrollo_QA ->TESTDIRNAME  ):
![image](https://user-images.githubusercontent.com/8714477/29990683-41d7b9fc-8f3a-11e7-84e2-e4c579e3be10.png)

Put the project files change owner and permissions:
![image](https://user-images.githubusercontent.com/8714477/29990660-0d0eb13a-8f3a-11e7-8c45-bf553611a5c2.png)


Remember Choose your allure report:
![image](https://user-images.githubusercontent.com/8714477/29990770-218334dc-8f3b-11e7-928f-b9bf0a0f25fc.png)

**Comment by ggerogery** [comment]
@shat00n 
Actually it's problem with wrong paths in pipeline.
My working example:

>     ...
>         stage('Browser tests'){
>             parallel {
>                 stage('Chrome'){
>                     steps {
>                         catchError {
>                             sh """
>                                pytest $PATH_SELEN/ui_desktop/test/test_desktop_smoke.py --alluredir=/var/lib/jenkins/workspace/allure_results --chrome=66 --url=${params.branch.toLowerCase()}
>                         """
>                         }
>                         echo currentBuild.result
>                     }
>                 }
>       ...
>     post {
>         always {
>             node('master') {
>             allure report: 'allure_reports', results: [[path: 'allure_results']]
>             }
>         }
>     }
>

**Comment by Lanuet** [comment]
hi, 
I get the same problem in JenkinsFile,
Here is my jenkinsFile:
`stage('reports') {
        steps {
        script {
                allure([
                        includeProperties: false,
                        jdk: '',
                        properties: [],
                        reportBuildPolicy: 'ALWAYS',
                        results: [[path: 'home/quynhpt/workspace/behave-test-pineline/results']]
                ])
                }
            }
        }
    }`
But i gotthe noti:
$/home/quynhpt/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/allure_commandline/bin/allure generate -c -o /home/quynhpt/workspace/behave-test-pineline/allure-report
allure-results does not exists
Report successfully generated to /home/quynhpt/workspace/behave-test-pineline/allure-report
Allure report was successfully generated.
Creating artifact for the build.
Artifact was added to the build.

And when i open allure report, i got empty report.
Anyone can help me?
Thank in advanced :D

**Comment by ggerogery** [comment]
@Lanuet 
Try this:
` stage('reports') { steps { script { allure([ includeProperties: false, jdk: '', properties: [], reportBuildPolicy: 'ALWAYS', results: [[path: 'allure-results']] ]) } } } }`

**Comment by Lanuet** [comment]
Hi @ggerogery 
I tried this but i got the same problem. nothing change :(

**Comment by Lanuet** [comment]
I resolve my problem.

When run shell script, need to define allure-results folder by: "-o %allure-results folder%"and put it in results path.

Thank u @ggerogery

**Comment by adrianrojas-j** [comment]
@Lanuet could you add the piece of pipeline? Please, I am having the same issue

**Comment by Lanuet** [comment]
Hi @adrianrojas-j 
Here is my Jenkinsfile:
`pipeline {
     agent {
        label 'Ubuntu_14'
    }
    stages {
        stage('test') {
            steps {
                sh 'behave -f allure_behave.formatter:AllureFormatter -o ./allure-results -D browser=chrome feature_file.feature'
            }
        }
     stage('reports') { steps { script { allure([ includeProperties: false, jdk: '', properties: [], reportBuildPolicy: 'ALWAYS', results: [[path: './allure-results']] ]) } } }
     }
     post('Publish report') {
        always {
                 script { allure([ includeProperties: false, jdk: '', properties: [], reportBuildPolicy: 'ALWAYS', results: [[path: './allure-results']] ]) }
          }
      }

}
`
I mean, you nead add the path to the allure-result folder by "-o ./allure-results"
Try this,
good luck
