### ISSUE TITLE
No back to Jenkins link 

### ISSUE THREAD

**Issue by yanivop** [jenkinsci/allure-plugin#158]
## Issue
After upgrading Jenkins plugin, the report name changes back to "Allure Test Pack" and tms links are broken.

### Context
- **Jenkins version**: 2.60.2
- **Job type**: Freestyle

- **Allure plugin version**: 2.22
- **Allure commandline version**: 1.4.23

### Problem description

I upgraded the plugin from version 2.10 to the latest 2.22, the back to Jenkins link is missing now and the  tms links are broken although they are set the same way as before the upgrade.

**Comment by eroshenkoam** [comment]
@yanivop Why are you using allure 1.4.23 instead of allure 2?

**Comment by vbragin** [comment]
@yanivop Try to use allure 2. If you will have a troubles with it please reopen this issue.
