### ISSUE TITLE
Smartsearch in categories and suites.

### ISSUE THREAD

**Issue by F1ashhimself** [jenkinsci/allure-plugin#168]
## Issue
Smartsearch like in IDEA or PyCharm in categories and suites.

### Context
- **Jenkins version**: 2.60.3
- **Job type**: Freestyle

- **Allure plugin version**: 2.23
- **Allure commandline version**: 2.4.1

### Problem description
It will be nice to have smart search, like implemented in IDEA or PyCharm ("[search everywhere](https://www.jetbrains.com/help/idea/searching-everywhere.html)" feature), that will ignore some characters.
![Search everywhere](https://i.imgur.com/eARqljR.png)

**Comment by eroshenkoam** [comment]
https://github.com/allure-framework/allure2/issues/633
