### ISSUE TITLE
Allure doesn't display files with some text/* content types (excepting text/plain).

### ISSUE THREAD

**Issue by F1ashhimself** [jenkinsci/allure-plugin#169]
## Issue
Allure doesn't display files with some text/* content types (excepting text/plain), it suggest you to download it. Found on mime type text/x-log.

### Context
- **Jenkins version**: 2.60.3
- **Job type**: Freestyle

- **Allure plugin version**: 2.23
- **Allure commandline version**: 2.4.1

### Problem description
It will be good to have ability to read these attachments in browser like actualy was in previous versions.

**Comment by eroshenkoam** [comment]
https://github.com/allure-framework/allure2/issues/632
