### ISSUE TITLE
Report link lead to 404 page if you set reportPath other than default ("allure-report").

### ISSUE THREAD

**Issue by andreybehalf** [jenkinsci/allure-plugin#178]
### Context
- **Jenkins version**: 2.60.1
- **Job type**: Pipeline

- **Allure plugin version**: 2.25
- **Allure commandline version**: 2.2.3b1

### Problem description

Trying to generate allure report with the new "reportPath" param in the new plugin version (2.25) - it seems like the generation works OK but the link isn't leading to the report but to 404 page.

I've tried to investigate the problem and it seems that you forgot to update the link to work with dynamic report path. 

In allure-plugin/src/main/java/ru/yandex/qatools/allure/jenkins/AllureReportPlugin.java causes the problem
`line 19: public static final String REPORT_PATH = "allure-report";
`

**Comment by vbragin** [comment]
@andreybehalf Hello, 
Try to use "report" instead "reportPath".
Please, write about your results here.

**Comment by andreybehalf** [comment]
@vbragin Hey, I actually was using this param in the first place so now I did run 2 jobs one with - "reportPath" and the second with "report" param and the conclusions are the following:
1. "report" param - when in the **same** job I run twice the generate report command for 2 different allure reports with different paths - I get 404 link for both buttons (If I do it with 1 report it will work).
2. "reportPath" - Both link lead to the latest report
---------
So the conclusion is that the link doesn't work when the report "icon" generated twice in the same job. Is this solvable? 
Thanks!

**Comment by vbragin** [comment]
@andreybehalf 
Currently there is no time to implement the possibility to generate more then one report in the same time. 
The better way is to generate one report from several results.
If it is critical for you, you can write a pull request for this issue.

**Comment by chenlujjj** [comment]
Is there any update on this issue? I face the same problem

**Comment by shanidar** [comment]
I have the same problem, any update?
