### ISSUE TITLE
[Feature request] Mark build as unstable if report contains failed or broken tests

### ISSUE THREAD

**Issue by da-yaroslav-orel** [jenkinsci/allure-plugin#181]
### Problem description
If Jenkins build contains failed tests allure plugin doesn't parse the results and doesn't mark build as unstable.

**Comment by vbragin** [comment]
Could you please try to use new plugin version: 2.25.1 and write about the results.
Looks like the it was fixed there.

**Comment by da-yaroslav-orel** [comment]
@vbragin Yep. Works like charm. Thanks. Think we can close this issue
