### ISSUE TITLE
History trend resets after a build that not generated Allure report

### ISSUE THREAD

**Issue by andreybehalf** [jenkinsci/allure-plugin#182]
### Context
- **Jenkins version**: 2.73.2
- **Job type**: Pipeline

- **Allure plugin version**: 2.25
- **Allure commandline version**: 2.2.3b1 (allure-python)

### Problem description
-Expected: History trend should be displayed and count in the previous reports.
-Actual: History trend don't count in the previous reports if the current report generated in a build 
that was ran after a build that failed/didn't generate an Allure report.

To reproduce - 
1. Run build that will generate Allure report with specific test
2. Run build that will fail on generating an Allure report.
3. Run build that will generate Allure report with same specific test from step #1
4. Check the test report in the last build and see there is no history trend for the first build

**Comment by vbragin** [comment]
@andreybehalf Hello Could you please have a look into builds log information.
Is there any NPE in it?

**Comment by vbragin** [comment]
@andreybehalf Could you please try to use new plugin version: 2.25.1 and write about the results.
Looks like the problem was fixed there.

**Comment by vbragin** [comment]
@andreybehalf Feel free to reopen the issue if this problem still exists.

**Comment by andreybehalf** [comment]
Thanks!
