### ISSUE TITLE
Allure Test Cases PASS even though Build step 'Invoke top-level Maven targets' marked build as failure"

### ISSUE THREAD

**Issue by aeroclee** [jenkinsci/allure-plugin#187]
### Context
- **Jenkins version**: jenkins-2.93
- **Job type**: Freestyle
- **Allure Jenkins Plugin**: 2.25
- **Allure Commandline Installation Version**: 2.4.1
- **Platform**:  Windows

### Problem description
Looks like this is the issue/bug.

I have Jenkins Build Failure due to configuration problem.
Red Mark on the Jenkins Build history.  However, when I click on the Allure report icon next to the build number and date, all my test cases are passed with green mark.

The reason of Build Failure is "Build step 'Invoke top-level Maven targets' marked build as failure".
None of test cases have even run yet, but indicated as Pass on the Allure Report.

Console Output:
Started by user anonymous
Building in workspace C:\Program Files (x86)\Jenkins\workspace\DV
[DV] $ cmd.exe /C '""C:\Program Files\Apache\maven\bin\mvn.cmd"' -f pom.xml clean test && exit %%ERRORLEVEL%%"
\Jenkins\workspace\DV was unexpected at this time.
Build step 'Invoke top-level Maven targets' marked build as failure
[DV] $ "C:\Program Files (x86)\Jenkins\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\Allure_Report\bin\allure.bat" generate "C:\Program Files (x86)\Jenkins\workspace\DV\target\allure-results" -c -o "C:\Program Files (x86)\Jenkins\workspace\DV\allure-report"
Report successfully generated to C:\Program Files (x86)\Jenkins\workspace\DV\allure-report
Allure report was successfully generated.
Creating artifact for the build.
Artifact was added to the build.
Finished: FAILURE

### Logs & Traces
Started by user anonymous
Building in workspace C:\Program Files (x86)\Jenkins\workspace\DV
[DV] $ cmd.exe /C '""C:\Program Files\Apache\maven\bin\mvn.cmd"' -f pom.xml clean test && exit %%ERRORLEVEL%%"
\Jenkins\workspace\DV was unexpected at this time.
Build step 'Invoke top-level Maven targets' marked build as failure
[DV] $ "C:\Program Files (x86)\Jenkins\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\Allure_Report\bin\allure.bat" generate "C:\Program Files (x86)\Jenkins\workspace\DV\target\allure-results" -c -o "C:\Program Files (x86)\Jenkins\workspace\DV\allure-report"
Report successfully generated to C:\Program Files (x86)\Jenkins\workspace\DV\allure-report
Allure report was successfully generated.
Creating artifact for the build.
Artifact was added to the build.
Finished: FAILURE

**Attached Reference File:**
![image](https://user-images.githubusercontent.com/32941858/33856808-2fd1dc40-de7e-11e7-8d45-68b9a96f0716.png)

**Comment by vbragin** [comment]
@aeroclee Allure plugin always create the reports base on the test's results wich are present in your job's working directory (example: "target/allure-results"). 
If the previous test results exists in working directory there is no problem (exceptions) to create a report. The plugin doesn't clean the results folder. You need to configure the job to have new results by youself.
Generally if you use maven, it does "clining" when executes for example "clean test" goals.
If for some reason the maven goals not executes and the old results exist then the report will be generated base on them.
So it is not a bug or issue.
If you expect a build without an report in case of failed, try to clean the previous results and execute the job again. 
Hope this will help.
Feel free to reopen the issue in case of other problems.
