### ISSUE TITLE
Allure Jenkins integration not working; no troubleshooting direction in documentation

### ISSUE THREAD

**Issue by osmolyar** [jenkinsci/allure-plugin#198]
### Context
- **Jenkins version**: 2.8
- **Job type**: , Matrix

- **Allure plugin version**: 2.26.0
- **Allure commandline version**: 2.6.0

### Problem description

Documentation on Allure Jenkins integration may be insufficient or could use a section on troubleshooting - where to look for generated Allure report on slave servers, for instance.

In my instance, an Allure report link and link to the allure-report.zip is generated on the job page, but both are empty (0 tests, 0 suites). I have installed the Allure plugin and allure-commandline to the Jenkins host and configured automatic installation to the slaves via configureTools.  Have also installed allure-comandline manually on each host and added to $PATH. However I am not sure how to check whether the allure reports are generated on the slaves or not (what is the target report directory relative to on the slaves?) Report generation does work using allure commandline when run locally.

**Comment by AvaJay** [comment]
@osmolyar Just wondering if you found a solution to your issue?  Thanks!

**Comment by osmolyar** [comment]
@AvaJay , yes, it's working fine now - don't recall what that specific issue was, unfortunately.  The console log (accessed via the job's Console Log link in Jenkins) may have some hints.
