### ISSUE TITLE
Allure report from .TRX files displays incorrect date 18/1/1970 consistently 

### ISSUE THREAD

**Issue by premaram** [jenkinsci/allure-plugin#200]
## Issue
Actual: Allure report from .TRX files displays incorrect date 18/1/1970 irrespective of any date generated
Expected: Should dynamically display the current date on the date the report actually generated

### Context
- **Jenkins version**: 2.60.2
- **Job type**: Pipeline, Freestyle, Matrix, etc.

- **Allure plugin version**: 2.26.0
- **Allure commandline version**: 2.6

### Problem description

_Describe your problem in a meaningful way_:
- I am trying to generate Allure report for the vstest results in .TRX format
- Report Overview tab should display the current date of report generation
- Report displays the date "18/1/1970" incorrectly always

### Logs & Traces

_Please include any relevant log that could serve to better understand the source of your issue_
![trx_report_date_error](https://user-images.githubusercontent.com/19297606/37054962-502f2e58-2135-11e8-8965-77f188566196.JPG)

**Comment by vbragin** [comment]
@premaram 
Could you provide an example of your .TRX file content.

**Comment by premaram** [comment]
Sure @vbragin 
Please find the attached and rename it to trx file as I am not allowed to attach a .TRX file
[FileTests_1.0.0.0_x64.txt](https://github.com/jenkinsci/allure-plugin/files/1804521/FileTests_1.0.0.0_x64.txt)

**Comment by premaram** [comment]
@vbragin Do you have any ETA on the fix?
Is this time generated from addTesetRunIfo( ) in AllureReportPublisher.java

**Comment by Atrifex** [comment]
I am able to reproduce this as well. For me, it is showing a time in the future instead of the past. See image below:
<img width="290" alt="Screen Shot 2019-04-07 at 9 28 24 PM" src="https://user-images.githubusercontent.com/12935724/55698740-331f0b00-597c-11e9-9448-96be4d43117a.png">.

**Comment by tobysainsbury** [comment]
I am having the same issue with a date of 1/19/1970. Did you find a solution to this?

**Comment by psiservices-aray** [comment]
This is actually an issue with Allure's trx-plugin. I submitted a PR today to fix it: https://github.com/allure-framework/allure2/pull/982. If you do not want to wait for it to be accepted, you can just build that jar, and place it on your Jenkins server. I am doing this currently in my environment.

**Comment by aaronmray** [comment]
This is actually an issue with Allure's trx-plugin. I submitted a PR today to fix it: https://github.com/allure-framework/allure2/pull/982. If you do not want to wait for it to be accepted, you can just build that jar, and place it on your Jenkins server. I am doing this currently in my environment.

**Comment by vbragin** [comment]
Looks like this was fixed https://github.com/allure-framework/allure2/pull/982
