### ISSUE TITLE
No such file or directory ./AllureCommandline/bin/allure

### ISSUE THREAD

**Issue by wendywww** [jenkinsci/allure-plugin#207]
### Context
- **Jenkins version**: Jenkins ver. 2.111
- **Job type**: Pipeline

- **Allure plugin version**: 2.26.0
- **Allure commandline version**: it's installed through the global tool setting, by maven central v2.6.0 

### Problem description

_Describe your problem in a meaningful way_:
- Installed jenkins allure plugin and commandline(I suspect problem is "the commandline isn't installed successfully" Saw most of successful example is from zip)
- After run the test, expect to have allure report generated through jenkins.
- Encountered error while generating the report: see screenshot below:
![screen shot 2018-04-30 at 11 46 03 am](https://user-images.githubusercontent.com/5750536/39453717-1138cdda-4c8c-11e8-930a-a40cd3aa6ccd.png)

Screen shot for commandline installer from global tools setting
![maven_commondline_install](https://user-images.githubusercontent.com/5750536/39453913-28fa475e-4c8d-11e8-91de-140e9858d1a9.png)

### Logs & Traces
**Error messages:**
```
/home/ec2-user/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/AllureCommandline/bin/allure generate -c -o /home/ec2-user/workspace/integration-tests-allure/allure-report

env: '/home/ec2-user/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/AllureCommandline/bin/allure': No such file or directory
```

**Under wdio.config**
```
reporters: ['dot', 'spec', 'junit', 'allure'],
reporterOptions: {
junit: {
outputDir: process.env.CIRCLE_TEST_REPORTS ? ${process.env.CIRCLE_TEST_REPORTS}/webdriverio/ : './logs/',
},
allure: {
outputDir: './allure-results'
}
```

**package-lock.json**
```
"wdio-allure-reporter": {
"version": "0.6.0",
"resolved": "https://registry.npmjs.org/wdio-allure-reporter/-/wdio-allure-reporter-0.6.0.tgz",
"integrity": "sha512-EMeNuCjrvL2qPzOHDomb3sfdNINC2RuaK4v80i8Lj1TZT08HMHZYqJbqxWsxrLH0py1LN1cOwKxzSUT++P5U/w==",
"dev": true,
"requires": {
"allure-js-commons": "1.3.1",
"babel-runtime": "6.26.0"
},
```

**package.json**
```"devDependencies": "wdio-allure-reporter": "^0.6.1"```

**jenkins file for pipline script:**
```
post {
always {
archiveArtifacts allowEmptyArchive: true, artifacts: 'integration/logs/.'
archiveArtifacts allowEmptyArchive: true, artifacts: 'integration/shots/.'
junit 'integration/logs/*.xml'
allure([includeProperties: false, jdk: '', properties: [[key: 'variant', value: '${VARIANT}']], reportBuildPolicy: 'ALWAYS',results: [[path: 'allure-results']]])
cleanWs()
}
}
```

Please help resolve this issue ASAP.  Thanks!

**Comment by wendywww** [comment]
@eroshenkoam Could you please take a look at this issue? Thank you:)

**Comment by eroshenkoam** [comment]
```
pipeline {
    agent { label 'java' }
    stages {
        stage('Run tests') {
            agent {
                docker {
                    reuseNode true
                    image 'maven'
                }
            }
            steps {
                // clone build-harness
               checkout([$class: 'GitSCM', branches: [[name: 'origin/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/allure-examples/allure-junit-example']]])
               sh 'mvn clean test -Dmaven.test.failure.ignore=true'
               stash name: 'allure-results', includes: 'target/allure-results/*'
            }
        }
    }
    post {
        always {
           unstash 'allure-results'
           allure results: [[path: 'target/allure-results']]
        }   
    }
}
```

**Comment by eroshenkoam** [comment]
@wendywww please test it

**Comment by eroshenkoam** [comment]
You need to use `stash-unstash` feature in this case.
With this feature the problem will be solved.

**Comment by wendywww** [comment]
<img width="1381" alt="fail_to_extract" src="https://user-images.githubusercontent.com/5750536/40881456-f6dc6afa-667b-11e8-87cd-3df7acf7eee4.png">
Thank you @eroshenkoam  This is the current error i am having after add stash-unstash in my .jenkins file.

**Comment by wendywww** [comment]
I tried both the options you suggested, but I am still getting the same errors. This seems from the ```java.nio.file.AccessDeniedException: /home/ec2-user/workspace/test-allure-integration@2/integration/allure-results/0008a34b-9c30-4e6b-ba93-84993298ebda-attachment.json ``` and```Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to slaves.jenkins-dev.mertslounge.ca (i-0b669f80dc65c18b3)``` I have attached the detailed error message here.

**Comment by wendywww** [comment]
@eroshenkoam I am not able to unstash the allure-results successful, which doesn't feed data to the allure report. I think it's very close now, do you have any suggestion on how to make unstash work? (as you suggested, the unstash is under `agent any`

**Comment by wendywww** [comment]
<img width="1183" alt="screen shot 2018-07-11 at 2 34 24 am" src="https://user-images.githubusercontent.com/5750536/42564609-14537134-84b6-11e8-8ac9-fe3df329d425.png">

**Comment by wendywww** [comment]
```
post {
        always{
            unstash 'allure-results' //unpack test results
            script {
                allure results: [[path: 'integration/allure-results']]
            }
        }
    }
```
by adding the script snippet `script {
                allure results: [[path: 'integration/allure-results']]
            }` the report is able to read the data from the results.   Hope this help others who's in same issue

**Comment by wendywww** [comment]
@eroshenkoam you can close this issue as we have resolved it long time back, thank you.
