### ISSUE TITLE
Empty(NaN%) report

### ISSUE THREAD

**Issue by ggerogery** [jenkinsci/allure-plugin#214]
### Allure commandline version: 2.7.0

**- what were you doing**

Hi, I'm facing a problem when trying to publish allure reports with multiple result directories. 
With single report directory is everything OK. But with multiple directories in **post** stage - I get empty report. Pipeline:

```
        stage('Browser tests'){
            parallel {
                stage('Chrome'){
                    agent any
                    steps {
                            sh """
                               pytest $PATH_SELEN/ui_desktop/test/test_desktop_smoke.py --alluredir=/var/lib/jenkins/workspace/allure-results/allure_results_chrome
                        """
                    }
                }
                stage('Firefox'){
                    agent any
                    steps {
                            sh """
                               pytest $PATH_SELEN/ui_desktop/test/test_desktop_smoke.py --alluredir=/var/lib/jenkins/workspace/allure-results/allure_results_chrome
                        """
                        }
                    }
                }  

      ...........

    post {
        always {
            node('master') {
                script {
                    allure([reportBuildPolicy: 'ALWAYS', results: [[path: 'allure-results/allure_results_chrome'], [path: 'allure-results/allure_results_firefox']]])
                }
            }

.......
```
Jenkins commandline settings: http://i.imgur.com/eP3vmYs.png

> /var/lib/jenkins/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/AllureMaven/bin/allure --version
> 2.7.0

**- what was expected**
Allure report from multiple results directories(results: [[path: 'allure-results/allure_results_chrome'], [path: 'allure-results/allure_results_firefox'], etc...]) in Jenkins UI

**- what occurred finally**
Empty report - http://i.imgur.com/HWBJLwF.png
Jenkins Pipeline output:

> /var/lib/jenkins/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/AllureMaven/bin/allure generate -c -o /var/lib/jenkins/workspace/docker_alpha_pet/allure-report
> allure-results does not exists
> Report successfully generated to /var/lib/jenkins/workspace/docker_alpha_pet/allure-report
> Allure report was successfully generated.
> Creating artifact for the build.
> Artifact was added to the build.

 @eroshenkoam

**Comment by lydialiu199403** [comment]
I am facing the same issue, any news?

Thanks for your help.

**Comment by ggerogery** [comment]
> I am facing the same issue, any news?
> 
> Thanks for your help.
Hi, 
Then in my case I was wrong with paths.
Now I run my tests cases with 'Jenkins Pipeline' and publish allure results via another 'Freestyle job'.
For example, one step in pipeline run tests and put results here -> "**/var/lib/jenkins/workspace/allure_report_chrome_beta_b2b/allure-results**". Freestyle job "allure_report_chrome_beta_b2b" only publish Allure reports and can be triggered from the Pipeline.

http://i.imgur.com/vw9iZ9G.png

**Comment by lydialiu199403** [comment]
@ggerogery Thanks a lot for your reply.

**Comment by achavva** [comment]
Without jenkins and using csharp code how to fix this error?
