### ISSUE TITLE
Allure report with jenkin: HTTP Status 404 – Not Found. The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

### ISSUE THREAD

**Issue by Lanuet** [jenkinsci/allure-plugin#226]
### Context
- **Jenkins version**: 2.150
- **Job type**: Freestyle

- **Allure plugin version**: 2.27
- Run on Apache Tomcat version: 9.0.12

### Problem description

I am facing a problem: I install jenkin plugin on jenkins. After job done, i click on the icon in the right of the build number, but i received notification: 
**Http Status 404 - Not found**
**Type**: Status Report

**Message:** /job/Demo_behave/40/allure

**Description**: The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.
### Logs & Traces
Link log: [Jenkins log]( https://gist.github.com/Lanuet/fd57dd894ecc936b279de7b789be54d9)

**Comment by gshefer** [comment]
I have the same issue :+1:

**Comment by NithyaRaji** [comment]
same issue for me too..

**Comment by teegalasv** [comment]
Any update on this ?? i am having same issue on jenkins when i generate report with a report path.

**Comment by Lanuet** [comment]
Hi, i fix it by using jenkin pineline
https://github.com/jenkinsci/allure-plugin/issues/156#issuecomment-464422555
