### ISSUE TITLE
Wrong test results in Jenkins Allure Report

### ISSUE THREAD

**Issue by ivanli1990** [jenkinsci/allure-plugin#227]
### Context
- **Jenkins version**: 2.46.3
- **Job type**: Pipeline

- **Allure plugin version**: 2.26.0
- **Allure commandline version**: 2.8.1

### Problem description

_Describe your problem in a meaningful way_:
- I used Jenkins Allure plugin to generate pytest testing results, and the pipeline is built periodically.
- The problem is the result in Jenkins Allure is not correct. Some pytest cases's results is not the latest running, but historical running. For example，I build the pipeline to run the case in 12.24, but some cases results in Jenkins Allure showed result in 12.21.  And When I view the suites.json's content，I find the time field in the case is wrong. And I also found the start time on Allure Overview is 12.21.
Why some cases not generate latest running result in Jenkins Allure?

### Logs & Traces
![image](https://user-images.githubusercontent.com/20061898/50389888-d8fe8f00-076a-11e9-9015-94459c0274a6.png)
![image](https://user-images.githubusercontent.com/20061898/50389876-ab194a80-076a-11e9-9cf0-92d83e3d2d5e.png)
![image](https://user-images.githubusercontent.com/20061898/50389899-fc293e80-076a-11e9-9419-c0dc78539e67.png)

_Please include any relevant log that could serve to better understand the source of your issue_

**Comment by richardol** [comment]
Hi,

I'm facing the exact same problem. Historical data causing my Jenkins  job to fail, even if the Selenium pytest itself is passed. 
...
09:33:00 ========================== 2 passed in 223.20 seconds ==========================
09:33:00 #### Deactivate Virtual Environment ####
09:33:00 Xvfb stopping
09:33:00 [SeleniumNodeUpgrade] $ /opt/allure/bin/allure generate /home/builduser/workspace/VoV/L2/AdditionalTests/job_dsl/SeleniumNodeUpgrade/tests/allure-results -c -o /home/builduser/workspace/VoV/L2/AdditionalTests/job_dsl/SeleniumNodeUpgrade/allure-report
09:33:02 Report successfully generated to /home/builduser/workspace/VoV/L2/AdditionalTests/job_dsl/SeleniumNodeUpgrade/allure-report
09:33:02 Allure report was successfully generated.
09:33:02 Creating artifact for the build.
09:33:03 Artifact was added to the build.
09:33:03 Build step 'Allure Report' changed build result to UNSTABLE
09:33:03 [BFA] Scanning build for known causes...
09:33:03 [BFA] No failure causes found
09:33:03 [BFA] Done. 0s
09:33:03 Notifying upstream projects of job completion
09:33:03 Join notifier cannot find upstream project: VoV/L2/AdditionalTests/job_dsl/SeleniumPipeline
09:33:03 Finished: UNSTABLE

**Comment by shankarmravi** [comment]
We have a framework where we run backend tests using nose-allure-plugin and UI tests using protractor. All the tests are added as part of declarative pipeline. But the catch we see that there are 400+ tests run in test results, but the Allure report just shows 290 tests. All the tests have been annotated properly.
<img width="1077" alt="Screenshot 2019-06-07 at 9 50 26 AM" src="https://user-images.githubusercontent.com/34864608/59081059-d0110c80-8909-11e9-9b2c-3d1597f2e9a2.png">
<img width="608" alt="Screenshot 2019-06-07 at 9 50 54 AM" src="https://user-images.githubusercontent.com/34864608/59081070-d901de00-8909-11e9-97c6-45cc0390494e.png">

**Comment by marcinlesek** [comment]
Any updates? @shankarmravi @richardol @ivanli1990 did you manage to solve it?

**Comment by marcinlesek** [comment]
Bumping maintainers also 😉 @qameta-ci @eroshenkoam @ehborisov any ideas? 🙏

**Comment by ivanli1990** [comment]
@marcinlesek It seems caused by the legacy allure result data files in Jenkins slave's workspace. When I add cleanWs() statement in pipeline, the problem solved, and the result data in Jenkins Allure is correct.

**Comment by okovpashko** [comment]
@ivanli1990 is this approach documented somewhere? I didn't find any mentions in docs that the `allure-results` directory must be cleared on each build to have the correct report generated.
Also, the issue is not always reproduced. Some builds pass after the failed one but some fail.

As the improvements, is this possible to add an option to clear the `allure-results` directory after the successful report generation and add an explicit record in the build log that the build is marked as unstable by Allure plugin?
