### ISSUE TITLE
Unable to install Allure plugin in jenkins

### ISSUE THREAD

**Issue by deploy-pando** [jenkinsci/allure-plugin#235]
### Context
- **Jenkins version**: X.Y.Z
- **Job type**: Pipeline, Freestyle, Matrix, etc.

- **Allure plugin version**: X.Y
- **Allure commandline version**: X.Y.Z

### Problem description

_Describe your problem in a meaningful way_:
- what was expected -- Plugin should install successfully
- what occurred finally -- unable to install plugin

### Logs & Traces
Caused: java.io.IOException: Failed to load http://updates.jenkins-ci.org/download/plugins/allure-jenkins-plugin/2.28.1/allure-jenkins-plugin.hpi to /var/lib/jenkins/plugins/allure-jenkins-plugin.jpi.tmp
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1144)
Caused: java.io.IOException: Failed to download from http://updates.jenkins-ci.org/download/plugins/allure-jenkins-plugin/2.28.1/allure-jenkins-plugin.hpi
<img width="1008" alt="Screenshot 2019-04-04 at 3 25 49 PM" src="https://user-images.githubusercontent.com/45348149/55546990-fd64f280-56ed-11e9-8f79-6464e9fe584b.png">

_Please include any relevant log that could serve to better understand the source of your issue_

**Comment by mvoitko** [comment]
@deploy-pando Have you resolved your issue?
