### ISSUE TITLE
Single Allure report for all combinations of a Matrix job

### ISSUE THREAD

**Issue by atrifex** [jenkinsci/allure-plugin#236]
### Context
- **Jenkins version**: 2.169
- **Job type**: Matrix

- **Allure plugin version**: 2.28.1
- **Allure commandline version**: 2.4.1

### Problem description
I am trying to generate a single allure report for all components of a matrix job. By looking at the documentation, I am not able to see a clear way to achieve this. 

My questions are the following:
1. Is it possible?
2. If so, then how do you do it?

### Logs & Traces
Don't have any since I am not sure how to implement.

**Comment by vbragin** [comment]
1. No
...
