### ISSUE TITLE
The link to the documetation is broken - http://wiki.qatools.ru/display/AL/Allure+Jenkins+Plugin 

### ISSUE THREAD

**Issue by ernestomedina17** [jenkinsci/allure-plugin#267]
## Issue
The link to the usage documentation is broken: http://wiki.qatools.ru/display/AL/Allure+Jenkins+Plugin 

### Context
- The link is published here:  https://plugins.jenkins.io/allure-jenkins-plugin/

### Problem description

_ 404 Not Found

### Logs & Traces
![image](https://user-images.githubusercontent.com/11928244/85432491-0a6b3d00-b551-11ea-8ea8-59bfa3c8a40e.png)

**Comment by ravidpatel** [comment]
It has gaps, but you can [view an archived version of the docs here](http://web.archive.org/web/20170711204944/http://wiki.qatools.ru/display/AL/Allure+Jenkins+Plugin). With this repo being deserted, I'd recommend trying the [Allure Gitter](https://gitter.im/allure-framework/allure-core) instead for anyone needing help. In fact, the most recent messages I see there is from yesterday and are a question and answer about configuring the Allure Jenkins plugin.

**Comment by ernestomedina17** [comment]
Thank you!

**Comment by rafis** [comment]
Documentation is here, isn't it?
https://docs.qameta.io/allure/#_pipeline_plugin
