### ISSUE TITLE
Cloud Version of Plugin

### ISSUE THREAD

**Issue by grndvl1** [jenkinsci/allure-plugin#268]
## Issue 
Plugin Needs to Work With Cloud Version of Jira.  Seems it would be simple enough but not sure how to structure this to make it work with Jira cloud installs.  Almost all our users use the Jira cloud not a local instance of it.  So would love our automation testing to be able to implement Allure results into our Jira tickets for pass fail testing with results

**Comment by vbragin** [comment]
sorry but it is really not clear what about this issue.
