### ISSUE TITLE
Updates? New releases?

### ISSUE THREAD

**Issue by pandoras-toolbox** [jenkinsci/allure-plugin#272]
I asked the IT guys to install this plugin into Jenkins. They are kinda reluctant because the plugin was not updated for a long time. I tried to explain that it most likely will work fine anyway, but still they are sceptic.

Can you shed light on why there are no new releases of this plugin for more than a year?

And what are the main benefits of the plugin? For instance, would the history tab in the Allure plugin also work if the Allure reports are generated by Gradle commands within the build script and then publishing a HTML report in a generic way in Jenkins?

**Comment by AFriemann** [comment]
considering that [this](https://github.com/jenkinsci/allure-plugin/pull/271) is open for over a month now without any progress I think your IT guys are not wrong.

**Comment by pandoras-toolbox** [comment]
The plugin works and is very useful, that is what matters much more than infrequent updates.

**Comment by AFriemann** [comment]
That's not the point. This plugin is currently blocking Jenkins version upgrades, which means it will most likely collide with your companies security and compliance requirements. It does with ours and it is actively blocking us from getting fixes in.

It's not about new features, it's about continued compatibility and security.

**Comment by pandoras-toolbox** [comment]
Unless this plugin is not broken, there is no need for a fix. Besides this, a Jenkins server should usually be within the DMZ and not publicly accessible.

**Comment by AFriemann** [comment]
I don't think you're following. The PR linked above is required for the plugin to work properly on newer Jenkins version. Without maintenance this project is dead.

**Comment by baev** [comment]
> Can you shed light on why there are no new releases of this plugin for more than a year?

Our team experiencing no issues with this plugin so far. And we have so many integrations to maintain so that's question on priority. 

> And what are the main benefits of the plugin? For instance, would the history tab in the Allure plugin also work if the Allure reports are generated by Gradle commands within the build script and then publishing a HTML report in a generic way in Jenkins?

It is only required to support history feature. 

> I don't think you're following. The PR linked above is required for the plugin to work properly on newer Jenkins version

Had no idea the plugin is not working properly on newer Jenkins. I'll assign one of my engineers to that issue.

> Without maintenance this project is dead.

We are really appreciate our community and contributions but please, don't forget that Allure Framework is open source project without sponsor behind (check it out https://opencollective.com/allure-report). That's why at most part our team is focused on paid solution called Allure TestOps (aka Allure Enterprise). For ASAP fixes our engineers are always open for paid support requests (email -- allure at qameta.io)

**Comment by pandoras-toolbox** [comment]
> I don't think you're following. The PR linked above is required for the plugin to work properly on newer Jenkins version. Without maintenance this project is dead.

I overlooked the link. For me the Allure plugin works on stable Jenkins version 2.249.3. 

If the problem is to download Allure Commandline automatically on a non-stable Jenkins version, that is no blocker usually, since it can be downloaded manually and configured in Jenkins. But it would be very good if it is fixed of course.

**Comment by pandoras-toolbox** [comment]
Thank you for your answers baev!

**Comment by baev** [comment]
https://github.com/jenkinsci/allure-plugin/releases/tag/2.29.0

**Comment by AFriemann** [comment]
thanks for the fix and release @baev - it wasn't my intention to sound dismissive, I know our QA really loves the tooling. we'd never get budget approved to have someone fix this and i'd have no way of fixing it myself in my limited time - so the only option from my end was to look for an alternative. still, I appreciate the work you put in.
