### ISSUE TITLE
version: 2.28.1 , java.util.zip.ZipException: error in opening zip file

### ISSUE THREAD

**Issue by Emmavv** [jenkinsci/allure-plugin#279]
### Context
- **Jenkins version**: 2.121.1
- **Allure plugin version**: 2.28.1
- **Allure commandline version**: 2.13.3

### Problem description
generate allure reports  fail

### Logs & Traces
`14:41:33 Report successfully generated to ./allure
14:41:33 xulichao,liqing,liyan02,yangyang03,zhangtingting01
14:41:33 xulichao,liqing,liyan02,yangyang03,zhangtingting01
14:41:33 fail_app: []
14:41:34 ERROR: Step ‘Allure Report’ aborted due to exception: 
14:41:34 java.util.zip.ZipException: error in opening zip file
14:41:34 	at java.util.zip.ZipFile.open(Native Method)
14:41:34 	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
14:41:34 	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
14:41:34 	at java.util.zip.ZipFile.<init>(ZipFile.java:120)
14:41:34 	at ru.yandex.qatools.allure.jenkins.utils.FilePathUtils.isHistoryNotEmpty(FilePathUtils.java:79)
14:41:34 	at ru.yandex.qatools.allure.jenkins.utils.FilePathUtils.getPreviousReportWithHistory(FilePathUtils.java:70)
14:41:34 	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.addHistory(AllureReportPublisher.java:420)
14:41:34 	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.prepareResults(AllureReportPublisher.java:389)
14:41:34 	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:230)
14:41:34 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
14:41:34 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
14:41:34 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
14:41:34 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
14:41:34 	at hudson.model.Build$BuildExecution.post2(Build.java:186)
14:41:34 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
14:41:34 	at hudson.model.Run.execute(Run.java:1819)
14:41:34 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
14:41:34 	at hudson.model.ResourceController.execute(ResourceController.java:97)
14:41:34 	at hudson.model.Executor.run(Executor.java:429)`

**Comment by lalithach** [comment]
Hi @Emmavv , is this issue fixed? I am seeing similar issue on allure plugin version 2.28.1. is there any fix for it?
