### ISSUE TITLE
Provide a way to define allure.issues.tracker.pattern globally

### ISSUE THREAD

**Issue by OLibutzki** [jenkinsci/allure-plugin#30]
Due to this document http://wiki.qatools.ru/display/AL/Allure+Jenkins+Plugin#AllureJenkinsPlugin-IssueTrackerintegration I have to do it in every job.

I would like to define a default globally with the possibility to override the global value in the job configuration.

**Comment by yanivop** [comment]
This feature exists on version 2.7, I downgraded instead of modifying all my Jenkins Jobs

**Comment by eroshenkoam** [comment]
i will do it today

**Comment by OLibutzki** [comment]
Thanks, any idea when there will be a release which includes this feature?

**Comment by eroshenkoam** [comment]
It's already realeased 2.9
