### ISSUE TITLE
Documentation listed on jenkins plugin page opens access denied page. 

### ISSUE THREAD

**Issue by mrslavchev** [jenkinsci/allure-plugin#318]
### Describe your use-case which is not covered by existing documentation.

This URL http://wiki.qatools.ru/display/AL/Allure+Jenkins+Plugin currently shows access denied page. 
This is the error message: 
I got an error when visiting wiki.qatools.ru/display/AL/Allure+Jenkins+Plugin.
Error code: 1020
Ray ID: 77c93e1bf8d677f7
Country: BG
Data center: vie02
IP: 46.10.149.120
Timestamp: 2022-12-20 14:59:34 UTC

**Comment by egomez99** [comment]
No work around have been found yet and unable to fix by ourselves. Really annoying and frustrating issue.

**Comment by vbragin** [comment]
Please use this doc:
https://docs.qameta.io/allure/#_jenkins
