### ISSUE TITLE
issue with getExecutable(launcher)

### ISSUE THREAD

**Issue by ykachube** [jenkinsci/allure-plugin#32]
Hi guys

having exception running allure on windows slave:

17:47:27 java.io.IOException: Cannot run program "/local/services/apache-tomcat-6.0.41/bin/e:/jenkins_slave1/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/grid/bin/allure.bat" (in directory "e:\jenkins_slave1\workspace\HB-single-tests-Allure"): CreateProcess error=2, The system cannot find the file specified
17:47:27    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1041)
17:47:27    at hudson.Proc$LocalProc.<init>(Proc.java:244)
17:47:27    at hudson.Proc$LocalProc.<init>(Proc.java:216)
17:47:27    at hudson.Launcher$LocalLauncher.launch(Launcher.java:816)
17:47:27    at hudson.Launcher$ProcStarter.start(Launcher.java:382)
17:47:27    at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1149)
17:47:27    at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1114)
17:47:27    at hudson.remoting.UserRequest.perform(UserRequest.java:118)
17:47:27    at hudson.remoting.UserRequest.perform(UserRequest.java:48)
17:47:27    at hudson.remoting.Request$2.run(Request.java:328)
17:47:27    at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
17:47:27    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
17:47:27    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
17:47:27    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
17:47:27    at hudson.remoting.Engine$1$1.run(Engine.java:63)
17:47:27    at java.lang.Thread.run(Thread.java:744)
17:47:27    at ......remote call to jenkins_slave_1(Native Method)
17:47:27    at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1413)
17:47:27    at hudson.remoting.UserResponse.retrieve(UserRequest.java:221)
17:47:27    at hudson.remoting.Channel.call(Channel.java:778)
17:47:27    at hudson.Launcher$RemoteLauncher.launch(Launcher.java:929)
17:47:27    at hudson.Launcher$ProcStarter.start(Launcher.java:382)
17:47:27    at hudson.Launcher$ProcStarter.join(Launcher.java:389)
17:47:27    at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:196)
17:47:27    at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:93)
17:47:27    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
17:47:27    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
17:47:27    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:726)
17:47:27    at hudson.model.Build$BuildExecution.post2(Build.java:185)
17:47:27    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:671)
17:47:27    at hudson.model.Run.execute(Run.java:1766)
17:47:27    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
17:47:27    at hudson.model.ResourceController.execute(ResourceController.java:98)
17:47:27    at hudson.model.Executor.run(Executor.java:381)
17:47:27 Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
17:47:27    at java.lang.ProcessImpl.create(Native Method)
17:47:27    at java.lang.ProcessImpl.<init>(ProcessImpl.java:385)
17:47:27    at java.lang.ProcessImpl.start(ProcessImpl.java:136)
17:47:27    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1022)
17:47:27    at hudson.Proc$LocalProc.<init>(Proc.java:244)
17:47:27    at hudson.Proc$LocalProc.<init>(Proc.java:216)
17:47:27    at hudson.Launcher$LocalLauncher.launch(Launcher.java:816)
17:47:27    at hudson.Launcher$ProcStarter.start(Launcher.java:382)
17:47:27    at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1149)
17:47:27    at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1114)
17:47:27    at hudson.remoting.UserRequest.perform(UserRequest.java:118)
17:47:27    at hudson.remoting.UserRequest.perform(UserRequest.java:48)
17:47:27    at hudson.remoting.Request$2.run(Request.java:328)
17:47:27    at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
17:47:27    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
17:47:27    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
17:47:27    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
17:47:27    at hudson.remoting.Engine$1$1.run(Engine.java:63)
17:47:27    at java.lang.Thread.run(Thread.java:744)

we have jenkins running on linux in tomcat
and windows slave

seems for some reason allure adds jenkins home to executable path on windows slave

we tried to play with build and node settings to override variables but with no luck

ended up hacking plugin with 

arguments.add(buildEnv.get("ALLURE_EXEC"));
instead of
arguments.add(commandline.getExecutable(launcher));

Could you please assist

thank you

**Comment by eroshenkoam** [comment]
could you print all build properties here?

**Comment by shaiban** [comment]
ALLURE_EXEC	e:\jenkins_slave1\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\grid\bin\allure.bat
ALLUSERSPROFILE	C:\ProgramData
ANT_HOME	d:\Software\Ant
APPDATA	C:\WINDOWS\system32\config\systemprofile\AppData\Roaming
BASE	e:\jenkins_slave1
CommonProgramFiles	C:\Program Files\Common Files
CommonProgramFiles(x86)	C:\Program Files (x86)\Common Files
CommonProgramW6432	C:\Program Files\Common Files
COMPUTERNAME	EVBYMINSD39E2
ComSpec	C:\WINDOWS\system32\cmd.exe
DYNAMO_HOME	D:\ATG\ATG10.1.1\home
DYNAMO_ROOT	D:\ATG\ATG10.1.1
ENDECA_CONF	D:\ATG\Endeca\PlatformServices\workspace
ENDECA_MDEX_ROOT	D:\ATG\Endeca\MDEX\6.3.0
ENDECA_REFERENCE_DIR	D:\ATG\Endeca\PlatformServices\reference
ENDECA_ROOT	D:\ATG\Endeca\PlatformServices\6.1.3
ENDECA_TOOLS_CONF	d:\ATG\Endeca\ToolsAndFrameworks\3.1.0\server\workspace
ENDECA_TOOLS_ROOT	d:\ATG\Endeca\ToolsAndFrameworks\3.1.0
FP_NO_HOST_CHECK	NO
HOME	e:\jenkins_slave1
JAVA_HOME	d:\Software\Java\jdk1.8
JAVA_VM	D:\Software\Java\jdk1.6\bin\java
LOCALAPPDATA	C:\WINDOWS\system32\config\systemprofile\AppData\Local
MVN_HOME	d:\Software\apache-maven\apache-maven-3.0.5
NUMBER_OF_PROCESSORS	8
ORACLE_UNQNAME	sup.minsk.com
OS	Windows_NT
PATH	%Path%;%JAVA_HOME%\bin;%MVN_HOME%\bin;%ANT_HOME%\bin;%SAFARI_HOME%
Path	C:\ProgramData\Oracle\Java\javapath;D:\Software\Java\jdk1.6\bin;D:\Software\Ant\bin;d:\Software\MW\wls103\server\native\win\x64;D:\Software\Oracle\product\11.2.0\dbhome_1\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\opscode\chef\bin;C:\opscode\chef\embedded\bin;D:\Software\TortoiseSVN\bin;D:\Software\MW\ohs111\bin;D:\Software\MW\ohs111\opmn\bin;D:\Software\MW\ohs111\opmn\lib;D:\Software\MW\ohs111\perl\bin;D:\ATG\Endeca\PlatformServices\6.1.3\perl;D:\ATG\Endeca\PlatformServices\6.1.3\perl\5.8.3\bin;D:\ATG\Endeca\PlatformServices\6.1.3\bin;D:\ATG\Endeca\PlatformServices\6.1.3\utilities;d:\Software\Safari;
PATHEXT	.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PERL5LIB	D:\ATG\Endeca\PlatformServices\6.1.3\perl;D:\ATG\Endeca\PlatformServices\6.1.3\perl\5.8.3\lib
PERLLIB	D:\ATG\Endeca\PlatformServices\6.1.3\perl;D:\ATG\Endeca\PlatformServices\6.1.3\perl\5.8.3\lib
PROCESSOR_ARCHITECTURE	AMD64
PROCESSOR_IDENTIFIER	Intel64 Family 6 Model 45 Stepping 7, GenuineIntel
PROCESSOR_LEVEL	6
PROCESSOR_REVISION	2d07
ProgramData	C:\ProgramData
ProgramFiles	C:\Program Files
ProgramFiles(x86)	C:\Program Files (x86)
ProgramW6432	C:\Program Files
PSModulePath	C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\
PUBLIC	C:\Users\Public
PWD	e:\jenkins_slave1
SERVICE_ID	jenkinsslave-e__jenkins_slave1
SystemDrive	C:
SystemRoot	C:\WINDOWS
TEMP	C:\WINDOWS\TEMP
TMP	C:\WINDOWS\TEMP
UATDATA	C:\WINDOWS\CCM\UATData\D9F8C395-CAB8-491d-B8AC-179A1FE1BE77
UnixUtils	D:\ATG\Endeca\PlatformServices\6.1.3\utilities
USERDOMAIN	MINSK
USERNAME	39E2$
USERPROFILE	C:\WINDOWS\system32\config\systemprofile
windir	C:\WINDOWS
windows_tracing_flags	3
windows_tracing_logfile	C:\BVTBin\Tests\installpackage\csilogfile.log
WINSW_EXECUTABLE	e:\jenkins_slave1\jenkins-slave.exe
WL_ROOT	d:\Software\MW


както так, в переменных нет пути на "/local/services/apache-tomcat-6.0.41/bin"

**Comment by TestAutomation85** [comment]
@shaiban I am also facing the same issue. How did you hack the plugin ? Thanks

**Comment by msr77** [comment]
@eroshenkoam  Is there a plan to fix this issue with a new release?

**Comment by alenickwork** [comment]
Same issue, extremely waiting for a fix.

Could you pelase provide any workaround for now?

**Comment by devstrat** [comment]
@eroshenkoam I'm having the same issue, would really appreciate a workaround or an estimation for the fix to be available, cheers.
Linux Master + Windows slave, 

> Report generation failed
> java.io.IOException: Cannot run program "**/usr/share/tomcat6/bin/**C:/jenkins/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/Allure_cli/bin/allure.bat" (in directory "C:\jenkins\workspace\Nosetests_take1"): CreateProcess error=2, The system cannot find the file specified

**Comment by itaimalek** [comment]
Also facing the same issue....
any hint on this?
