### ISSUE TITLE
Migrate from Gradle and `gradle-jpi-plugin` to Maven and `maven-hpi-plugin`

### ISSUE THREAD

**Issue by basil** [jenkinsci/allure-plugin#321]
Gradle and `gradle-jpi-plugin` are no longer a fully supported build system for Jenkins plugins. `allure-plugin` is the second most popular non-deprecated Jenkins plugin built with Gradle and `gradle-jpi-plugin`.

Our fully supported build system for Jenkins plugins is Maven and `maven-hpi-plugin`. To ensure the long-term viability of `allure-plugin`, we recommend migrating to Maven and `maven-hpi-plugin`.

For examples, see https://github.com/jenkinsci/ivy-plugin/pull/49 and https://github.com/jenkinsci/job-dsl-plugin/pull/1265.

CC @eroshenkoam

**Comment by vbragin** [comment]
Will be done with #322
