### ISSUE TITLE
Can't launch plugin, "java.lang.NoClassDefFoundError:..." appeared

### ISSUE THREAD

**Issue by d-konovalov** [jenkinsci/allure-plugin#38]
Hi guys, 
I would like to use your tool. It works if I generate reports locally with allure-cli. But I still can't make it work on Jenkins. 

Here is console output:

![my screenshot](http://content.screencast.com/users/dmitrykonovalov/folders/Jing/media/89ae74d3-e7f8-40c0-ad3d-54be98e28aad/2015-12-03_1025.png)

When I open Environment variables page for current build I can't find anything related to Allure there

Please help me to find mistake I've made during installation

Thank you in advance

**Comment by d-konovalov** [comment]
This one appears as well
![one more image](http://content.screencast.com/users/dmitrykonovalov/folders/Jing/media/abc23c29-f464-4a5e-aafb-7690e53c2664/2015-12-03_1611.png)

**Comment by eroshenkoam** [comment]
which version of the plugin do you use?

**Comment by eroshenkoam** [comment]
https://developer.jboss.org/thread/152291?start=0&tstart=0

**Comment by d-konovalov** [comment]
I use the last version available 2.9

**Comment by eroshenkoam** [comment]
I test latest version (2.10) of allure-plugin on windows xp and windows 10. It's works. Which version of windows you are using?

**Comment by d-konovalov** [comment]
win10
I'll try to update plugin to 2.10

**Comment by d-konovalov** [comment]
Now it has the same view as the second screenshot

**Comment by eroshenkoam** [comment]
It looks like Jenkins further escapes file paths. On my screenshot every path looks like: "<path>". In your case, he adds, it looks like this: '"<path>"'. Which version of Jenkins are you using?
![2015-12-08 15 55 33](https://cloud.githubusercontent.com/assets/781455/11656253/d0442734-9dc4-11e5-8a07-7724f27690c0.png)

**Comment by d-konovalov** [comment]
Hi @eroshenkoam 
current version is 1.638
thank you

**Comment by lanwen** [comment]
@d-konovalov think propblem is in spaces in your path. Try to remove any from args.

(@eroshenkoam will think how to fix that)

**Comment by d-konovalov** [comment]
@lanwen Thank you
it works now!
