### ISSUE TITLE
Unable to setup Allure on Jenkins

### ISSUE THREAD

**Issue by poohpeer** [jenkinsci/allure-plugin#40]
I'm trying to configure Allure with Jenkins, but there are an errors that I can't get through.
1. encoding issue
2. Jenkins complete the run cycle with "Waiting for Jenkins to finish collecting data" and never update it.

[ Cant_set_encoding.txt](https://github.com/allure-framework/allure-core/files/62346/Cant_set_encoding.txt)

**Allure version:** 1.4.19
**Jenkins version:** 1.610
**Results file location:** /var/lib/jenkins/workspace/selenium/target/allure-results
Seems the results files get created successfully, but somehow Allure doesn't create the link for reports.

[eade93c4-4624-44d2-9560-8aaa6211bb54-testsuite.xml.zip](https://github.com/allure-framework/allure-core/files/62230/eade93c4-4624-44d2-9560-8aaa6211bb54-testsuite.xml.zip)

**Allure Commandline installations**
![Allure Commandline installations](https://cloud.githubusercontent.com/assets/7508122/11806244/7375e9e2-a31a-11e5-9d5f-d0df60704679.png)

**Post-build Actions**
![Post-build Actions](https://cloud.githubusercontent.com/assets/7508122/11806388/5690b068-a31b-11e5-9c88-85fbf2229b26.png)

Thanks

**Comment by baev** [comment]
*WARN  AllureResultsUtils:198 Can't set "jaxb.encoding" property to given marshaller* - just a warning, you can ignore it as well. But it is **1.4.4** only issue (see https://github.com/allure-framework/allure-core/releases/tag/allure-core-1.4.5). 1.4.19 should be fine

**Comment by poohpeer** [comment]
Can you suggest something, please?
https://stackoverflow.com/questions/34744469/allure-jenkins-report-is-not-generated

**Comment by baev** [comment]
all should be fine in `2.11`
