### ISSUE TITLE
Add standard Output

### ISSUE THREAD

**Issue by romainlouvet** [jenkinsci/allure-plugin#41]
Is-it possible to add standard Output attachement like Junit result in Jenkins ?

**Comment by vania-pooh** [comment]
Are you speaking about adding Allure attachment or this is about adding some elements to Jenkins interface?

**Comment by romainlouvet** [comment]
![capture d ecran 2016-01-13 a 14 11 51](https://cloud.githubusercontent.com/assets/4262374/12295184/aceb4932-b9ff-11e5-8e17-88b82f2103b9.png)
Add standard Output after stacktrace.

**Comment by vania-pooh** [comment]
To add attachment with any string just do the [following](https://github.com/allure-framework/allure-core/wiki/Attachments):
* Add method annotated with @Attachment annotation that returns either String or byte[]
* Call this method in some test case logic
After doing this generate Allure as usually and you will see attachment data under selected test case

**Comment by romainlouvet** [comment]
https://github.com/allure-framework/allure-core/issues/420
