### ISSUE TITLE
Link to next/previous build

### ISSUE THREAD

**Issue by georgecrawford** [jenkinsci/allure-plugin#42]
It'd be really useful if you could add in a link to the previous and next build, in the same way a link is already provided back to the current build.

Something like this:
![screenshot 2016-01-12 10 54 41](https://cloud.githubusercontent.com/assets/84737/12261769/34fdc7fe-b91b-11e5-92e5-e6a3e5aab6e6.png)

**Comment by vania-pooh** [comment]
@eroshenkoam what do you think?

**Comment by eroshenkoam** [comment]
You can navigate to previous build from Trend in Allure 2
