### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by eroshenkoam** [jenkinsci/allure-plugin#44]
итак, резюмирую:
1) в команде, которую формирует Jenkins лишние одинарные кавычки. экранирование вида '"command_text"' не работает. экранирование вида "command_text" работает
2) репорт не хочет билдиться, если в пути присуствует пробел, т.е. из папки C:\Program Files (x86) - не пашет. из всех других - все отлично
3) непонятно почему аллюр пытается заюзать некую "C:\Program Files (x86)\Jenkins\workspace\Example\allure4270908192639890012.tmp\environment", хотя настройка Include build environment в конфиге джобы снята
4) непонятно почему аллюр щемится в папку формата allure4270908192639890012.tmp\allure-report, хотя на уровне конфига джобы в Allure Result/Results: указано target\allure-results

**Comment by AlexanderPoleschuk** [comment]
небольшой апдейт по этому косяку: 
я перенес Jenkins из C:\Program Files (x86) в C:\Program Files и репорт сбилдился! 
так что проблема именно в пробеле в Installation directory Дженкинса и workaround есть!
как перенести Jenkins Install directory: http://stackoverflow.com/questions/12689139/how-to-change-jenkins-default-folder-on-windows

**Comment by eroshenkoam** [comment]
Fix #70
