### ISSUE TITLE
Allure Commandline setup moved to configureTools from configure in Jenkins 2.0

### ISSUE THREAD

**Issue by CodeChameleon** [jenkinsci/allure-plugin#48]
Setting up the Jenkins-Allure Plugin in Jenkins 2.0 has changed from the instructions given in [http://wiki.qatools.ru/display/AL/Allure+Jenkins+Plugin](http://wiki.qatools.ru/display/AL/Allure+Jenkins+Plugin). The instructions state that to setup the Commandline details to go to **/configure** however in Jenkins 2.0 this setup is done in **/configureTools**.

When creating the post build action to initiate the Allure report generation the error message states: 

> Jenkins needs to know where your Allure Commandline is installed.
> Please do so from the system configuration.

With the last sentence being a link back to **/configure** instead of **/configureTools**.

Could the online instructions and the Post Build Actions error message be updated to include this change for Jenkins 2.0.

**Comment by CodeChameleon** [comment]
The only issue is where the Allure configure settings moved in version 2.0. In Jenkins 2.0 those settings can be found in /configureTools instead of /configure

**Comment by sixsixtrample** [comment]
@CodeChameleon you are my hero. I was banging my head against my desk.

Thank you for this!

**Comment by mgawinec** [comment]
Can you please update the documentation?

http://wiki.qatools.ru/display/AL/Allure+Jenkins+Plugin#AllureJenkinsPlugin-Jobconfiguration

I've already reported this as a bug in documentation

http://stackoverflow.com/questions/40808956/how-to-configure-allure-jenkins-plugin

**Comment by eroshenkoam** [comment]
fixed
