### ISSUE TITLE
jenkins 2.0 support

### ISSUE THREAD

**Issue by allustin** [jenkinsci/allure-plugin#50]
9 days ago introduced https://github.com/jenkinsci/jenkins/commit/ae8f650bd90dd2fe087b18eecd7c5c8b7ed0a93f

Jenkins 2.0 ready for ship, there is meetup of what http://www.meetup.com/Jenkins-online-meetup/events/230154841/

is any plans for adopt allure-jenkins for Jenkins 2.0 ?

**Comment by eroshenkoam** [comment]
fixed #70
