### ISSUE TITLE
Jenkins - “Error: Could not find or load main class ru.yandex.qatools.allure.CommandLine”

### ISSUE THREAD

**Issue by Iryna-** [jenkinsci/allure-plugin#52]
I'm still getting this problem on Mac - http://stackoverflow.com/questions/36814163/allure-for-jenkins-on-osx-getting-error-could-not-find-or-load-main-class-ru

**Comment by baev** [comment]
@Iryna- hi again! Thanks for suggestion. 

It is a known problem, we gonna fix it ASAP.

**Comment by aroramayank2002** [comment]
I have plugin version 2.10 on mac, Jenkins version 2.11, and getting this error.
From withing the job folder if I execute "allure generate allure-results -o allure-reports" it works.

Job console output

/usr/local/lib/node_modules/allure-commandline/bin/allure generate "/Users/Shared/Jenkins/Home/workspace/<projectroot/projectpath >/allure-results" "/Users/Shared/Jenkins/Home/workspace/<projectroot>/allure7260197998731528257.tmp/environment" -o "/Users/Shared/Jenkins/Home/workspace/<projectroot>/allure7260197998731528257.tmp/allure-report"
Error: Could not find or load main class ru.yandex.qatools.allure.CommandLine

**Comment by bengineer-** [comment]
Any update on the proposed fix from @eroshenkoam ? I tried building it locally, but have some findbugs issues. Would be good to be able to use the allure auto installer on slave instances without having to hardcode the path.

**Comment by eroshenkoam** [comment]
fixed in #70
