### ISSUE TITLE
Allure plugin cannot resolve environment variables in properties

### ISSUE THREAD

**Issue by RocketRaccoon** [jenkinsci/allure-plugin#55]
Allure plugin cannot resolve environment variables in properties e.g. try to set 
`allure.tests.management.pattern = http://test-management/$
{BRANCH}?search=%s`

`${BRANCH}` variable is not resolved, result is `http://test-management/$BRANCH?search=TEST-13287`

Also there is no way to pass allure.properties file to Allure plugin.

See [JENKINS-36270](https://issues.jenkins-ci.org/browse/JENKINS-36270)

**Comment by RocketRaccoon** [comment]
Any updates on issue?

**Comment by danieldatri** [comment]
Hi @RocketRaccoon I had the same problem trying to configure the issue tracker and test management url as properties into the plugin.
The way I fixed was by sending those properties directly on maven goal 
```
mvn integration-tests -Dallure.issues.tracker.pattern="https://www.myissuetracker.com/browse/%s" -Dallure.tests.management.pattern="https://www.mytestcasemanagement.com/cases/view/%s"
```

**Comment by RocketRaccoon** [comment]
Hi @danieldatri,

Your solution sounds well, but does not work for me because we are running tests as jar file e.g.
`java -classpath "test-common.jar:*" org.testng.TestNG testng_suite.xml`
