### ISSUE TITLE
Different urls on report links

### ISSUE THREAD

**Issue by ex3me0** [jenkinsci/allure-plugin#59]
Sometimes links to reports is generated with "Jenkins URL" parameter (http://prntscr.com/c49949), but predominantly used the actual domain, that in browsers address bar (document.domain, correctly): http://prntscr.com/c49am8

This may cause some difficulties when using Jenkins behind NAT, or local/localhost URL used in "Jenkins URL"

**Comment by baev** [comment]
@ex3me0 Hi! Sorry for the delay

Allure Jenkins Plugin doesn't handle urls (it only specifies relative path, Jenkins builds absolute one by yourself)
