### ISSUE TITLE
Allure plugin does not load under jobs, it works fine for a particular build.

### ISSUE THREAD

**Issue by jinxac** [jenkinsci/allure-plugin#60]
I have a job in which I used allure-plugin. I did the steps mentioned in the allure-plugin documentation.

It is working fine for a particular build but if I try to open allure for a job it throws content privacy error as can be seen in the attached screenshot.
![screen shot 2016-08-22 at 6 05 47 pm](https://cloud.githubusercontent.com/assets/15068096/17854882/1550bc40-6893-11e6-9b43-98539715deb6.png)

**Comment by baev** [comment]
Hi! Sorry for the delay. See http://wiki.qatools.ru/display/AL/Allure+Jenkins+Plugin#AllureJenkinsPlugin-configure-security
