### ISSUE TITLE
Allure plugin unable to build the report

### ISSUE THREAD

**Issue by gkiszczak** [jenkinsci/allure-plugin#61]
I have linux jenkins master and my job is running on windows slave machine. 
My allure plugin is using 1.4.23 hotfix version of cli. 
I'm using following settings: 
![image](https://cloud.githubusercontent.com/assets/6102748/17974582/f76edfe4-6ae6-11e6-98e7-55e4cd5c4cdd.png)

Unfortunately while generating report I'm getting error:
Invalid JAVA_HOME: /usr/java/default is not a valid java directory 
Build step 'Allure Report' marked build as failure

I tried to use jdk-default as jdk settings and it doesn't help.
What can I do?

**Comment by eroshenkoam** [comment]
Try latest version of allure plugin, please
