### ISSUE TITLE
Reports Broken On Jenkins 1.651.3 Version

### ISSUE THREAD

**Issue by sharadJay** [jenkinsci/allure-plugin#63]
We recently got our jenkins upgraded and I dont see reports being generated any more. I think this can be related to jenkins policy of serving html content. Pasting screenshot with console

![image](https://cloud.githubusercontent.com/assets/5979667/18942034/86f3ced8-8633-11e6-88b6-71c7643bf8a0.png)

**Comment by baev** [comment]
@sharadJay see http://wiki.qatools.ru/display/AL/Allure+Jenkins+Plugin#AllureJenkinsPlugin-configure-security
