### ISSUE TITLE
Exception in thread "main" java.lang.NumberFormatException: For input string: ""

### ISSUE THREAD

**Issue by monolithed** [jenkinsci/allure-plugin#67]
####  Used plugins

allure-jenkins-plugin: 2.10
wdio-allure-reporter: 0.1.2

#### Error

```
14:14:21 $ /var/lib/selenium/jenkins-slave/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/1.4.24RC3-NEWFACE/bin/allure generate "/var/lib/selenium/jenkins-slave/workspace/yoda.runner/tests/cache/reports/allure-results" "/var/lib/selenium/jenkins-slave/workspace/yoda.runner/allure6050067575725090175.tmp/environment" -o "/var/lib/selenium/jenkins-slave/workspace/yoda.runner/allure6050067575725090175.tmp/allure-report"s
14:14:26 Exception in thread "main" java.lang.NumberFormatException: For input string: ""
14:14:26 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
14:14:26 	at java.lang.Long.parseLong(Long.java:601)
14:14:26 	at java.lang.Long.valueOf(Long.java:803)
14:14:26 	at com.sun.xml.internal.bind.DatatypeConverterImpl._parseLong(DatatypeConverterImpl.java:118)
14:14:26 	at ru.yandex.qatools.allure.model.TestCaseResult_JaxbXducedAccessor_stop.parse(TransducedAccessor_field_Long.java:50)
14:14:26 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.StructureLoader.startElement(StructureLoader.java:195)
14:14:26 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:559)
14:14:26 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:538)
14:14:26 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:153)
14:14:26 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
14:14:26 	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:380)
14:14:26 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2781)
14:14:26 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
14:14:26 	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
14:14:26 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504)
14:14:26 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
14:14:26 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
14:14:26 	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
14:14:26 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
14:14:26 	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
14:14:26 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243)
14:14:26 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:221)
14:14:26 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:276)
14:14:26 	at javax.xml.bind.JAXB.unmarshal(JAXB.java:242)
14:14:26 	at ru.yandex.qatools.allure.commons.AllureFileUtils.unmarshal(AllureFileUtils.java:59)
14:14:26 	at ru.yandex.qatools.allure.commons.AllureFileUtils.unmarshal(AllureFileUtils.java:50)
14:14:26 	at ru.yandex.qatools.allure.commons.AllureFileUtils.unmarshal(AllureFileUtils.java:40)
14:14:26 	at ru.yandex.qatools.allure.data.io.TestSuiteReader$TestSuiteResultIterator.next(TestSuiteReader.java:48)
14:14:26 	at ru.yandex.qatools.allure.data.io.TestSuiteReader$TestSuiteResultIterator.next(TestSuiteReader.java:1)
14:14:26 	at ru.yandex.qatools.allure.data.io.TestCaseReader$TestCaseResultIterator.nextSuite(TestCaseReader.java:46)
14:14:26 	at ru.yandex.qatools.allure.data.io.TestCaseReader$TestCaseResultIterator.hasNext(TestCaseReader.java:56)
14:14:26 	at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:63)
14:14:26 	at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:53)
14:14:26 	at ru.yandex.qatools.allure.AllureMain.main(AllureMain.java:48)
14:14:26 Command aborted due to exception {}.
14:14:26 org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
14:14:26 	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
14:14:26 	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
14:14:26 	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
14:14:26 	at ru.yandex.qatools.allure.command.ReportGenerate.runUnsafe(ReportGenerate.java:48)
14:14:26 	at ru.yandex.qatools.allure.command.AbstractCommand.run(AbstractCommand.java:52)
14:14:26 	at ru.yandex.qatools.allure.CommandLine.main(CommandLine.java:46)
14:14:26 Build step 'Allure Report' marked build as failure
14:14:26 Finished: FAILURE
```

#### System Properties

|  Name  | Value |
|--------|-------|
| awt.toolkit | sun.awt.X11.XToolkit |
| executable-war | /usr/share/jenkins/jenkins.war |
| file.encoding | UTF-8 |
| file.encoding.pkg | sun.io |
| file.separator | / |
| hudson.diyChunking | true |
| hudson.model.DirectoryBrowserSupport.CSP | default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; |
| hudson.model.ParametersAction.keepUndefinedParameters | true |
| hudson.model.ParametersAction.safeParameters | true |
| java.awt.graphicsenv | sun.awt.X11GraphicsEnvironment |
| java.awt.headless | true |
| java.awt.printerjob | sun.print.PSPrinterJob |
| java.class.path | /usr/share/jenkins/jenkins.war |
| java.class.version | 52.0 |
| java.endorsed.dirs | /usr/lib/jvm/java-8-oracle/jre/lib/endorsed |
| java.ext.dirs | /usr/lib/jvm/java-8-oracle/jre/lib/ext:/usr/java/packages/lib/ext |
| java.home | /usr/lib/jvm/java-8-oracle/jre |
| java.io.tmpdir | /tmp |
| java.library.path | /usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib |
| java.runtime.name | Java(TM) SE Runtime Environment |
| java.runtime.version | 1.8.0_91-b14 |
| java.specification.name | Java Platform API Specification |
| java.specification.vendor | Oracle Corporation |
| java.specification.version | 1.8 |
| java.vendor | Oracle Corporation |
| java.vendor.url | http://java.oracle.com/ |
| java.vendor.url.bug | http://bugreport.sun.com/bugreport/ |
| java.version | 1.8.0_91 |
| java.vm.info | mixed mode |
| java.vm.name | Java HotSpot(TM) 64-Bit Server VM |
| java.vm.specification.name | Java Virtual Machine Specification |
| java.vm.specification.vendor | Oracle Corporation |
| java.vm.specification.version | 1.8 |
| java.vm.vendor | Oracle Corporation |
| java.vm.version | 25.91-b14 |
| javamelody.About Monitoring | https://wiki.jenkins-ci.org/display/JENKINS/Monitoring |
| javamelody.analytics-id | UA-1335263-7 |
| javamelody.custom-reports | Jenkins Info,About Monitoring |
| javamelody.gzip-compression-disabled | true |
| javamelody.http-transform-pattern | /\d+/\|/site/.+\|avadoc/.+\|/ws/.+\|obertura/.+\|estReport/.+\|iolations/file/.+\|/user/.+\|/static/\w+/\|/adjuncts/\w+/\|/bound/[\w\-]+ |
| javamelody.Jenkins Info | /systemInfo |
| javamelody.no-database | true |
| javamelody.storage-directory | //var/lib/jenkins/monitoring |
| javamelody.system-actions-enabled | true |
| jenkins.model.DirectoryBrowserSupport.CSP | default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; |
| jna.loaded | true |
| jna.platform.library.path | /usr/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:/lib64:/usr/lib:/lib:/usr/lib/x86_64-linux-gnu/libfakeroot |
| jnidispatch.path | /tmp/jna--1712433994/jna5470802734352065393.tmp |
| line.separator | |
| mail.smtp.sendpartial | true |
| mail.smtps.sendpartial | true |
| os.arch | amd64 |
| os.name | Linux |
| os.version | 4.2.0-38-generic |
| path.separator | : |
| pid | 17889 |
| sun.arch.data.model | 64 |
| sun.boot.class.path | /usr/lib/jvm/java-8-oracle/jre/lib/resources.jar:/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jsse.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jce.jar:/usr/lib/jvm/java-8-oracle/jre/lib/charsets.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfr.jar:/usr/lib/jvm/java-8-oracle/jre/classes |
| sun.boot.library.path | /usr/lib/jvm/java-8-oracle/jre/lib/amd64 |
| sun.cpu.endian | little |
| sun.cpu.isalist | |
| sun.font.fontmanager | sun.awt.X11FontManager |
| sun.io.unicode.encoding | UnicodeLittle |
| sun.java.command | /usr/share/jenkins/jenkins.war --webroot=/var/cache/jenkins/war --httpPort=8080 |
| sun.java.launcher | SUN_STANDARD |
| sun.jnu.encoding | UTF-8 |
| sun.management.compiler | HotSpot 64-Bit Tiered Compilers |
| sun.os.patch.level | unknown |
| svnkit.http.methods | Digest,Basic,NTLM,Negotiate |
| svnkit.ssh2.persistent | false |
| user.country | RU |
| user.dir | / |
| user.home | /var/lib/jenkins |
| user.language | ru |
| user.name | jenkins |
| user.timezone | Europe/Moscow |

**Comment by jaysirju** [comment]
Heads up that this is an issue with allure-js-common library.
There's an open issue at https://github.com/allure-framework/allure-js-commons/issues/22

**Comment by baev** [comment]
@jaysirju is right, there is nothing to do with jenkins plugin
