### ISSUE TITLE
NPE with AllureReportPublisherDescriptor

### ISSUE THREAD

**Issue by mgawinec** [jenkinsci/allure-plugin#69]
When running a job with Allure Jenkins Plugin 2.10 on Jenkins ver. 2.24 I have received the following error message

> ERROR: Build step failed with exception
> java.lang.NullPointerException
> 	at ru.yandex.qatools.allure.jenkins.AllureReportPublisherDescriptor.getCommandlineInstallation(AllureReportPublisherDescriptor.java:98)
> 	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:147)
> 	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:93)
> 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
> 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
> 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
> 	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1047)
> 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
> 	at hudson.model.Run.execute(Run.java:1745)
> 	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:531)
> 	at hudson.model.ResourceController.execute(ResourceController.java:98)
> 	at hudson.model.Executor.run(Executor.java:404)
> Build step 'Allure Report' marked build as failure

What does this cryptic NPE message stands for?

Have I misconfigured anything?

**Comment by eroshenkoam** [comment]
@mgawinec, can you check it on v2.12?

**Comment by eroshenkoam** [comment]
https://github.com/jenkinsci/allure-plugin/blob/allure-jenkins-plugin-
2.10/src/main/java/ru/yandex/qatools/allure/jenkins/AllureReportPublisherDescriptor.java#L98
May be you misconfigurate the name of tool?
