### ISSUE TITLE
Empty allure report

### ISSUE THREAD

**Issue by kmoorits** [jenkinsci/allure-plugin#71]
I have a question about allure jenkins plugin.

We're currently trying to open allure report but it's empty. Allure reports are successfully generated to slaves directory. But when we click on the allure reports icon which should contain results, it shows nothing.
Is it possible that although reports are generated successfully to the slave node, jenkins master will search the reports to open from master itself?

If so, how can i change it to open the allure reports from node directory?

Jenkins ver. 2.32
Allure jenkins plugin 2.10

**Comment by velanbabu** [comment]
I'm also facing same issues.Request any one to update please.

**Comment by kmoorits** [comment]
Velanbabu, what OS are you using?

**Comment by eroshenkoam** [comment]
fixed #70
