### ISSUE TITLE
Unable to generate reports when running concurrent builds

### ISSUE THREAD

**Issue by sheg** [jenkinsci/allure-plugin#76]
Jenkins allows you to configure your job to allow builds to run concurrently so that long running builds do not block and queue up others. When builds run concurrently, the latest one cannot find the allure report. 

Given the following successful output below, it appears that the report is generated to a static location. I know you can dynamically specify where test results live, however, I am not sure if there is a way to dynamically specify where to generate the report. Perhaps this is the problem?

![screen shot 2017-02-01 at 11 42 48 am](https://cloud.githubusercontent.com/assets/2872749/22516518/06c13d9c-e874-11e6-82e6-9cbfd07da69f.png)

Here is the error you see:

![screen shot 2017-02-01 at 11 43 48 am](https://cloud.githubusercontent.com/assets/2872749/22516525/0db07974-e874-11e6-9f17-d1ccd6597268.png)

Do we know if concurrent build execution is supported?

Jenkins Version: 2.32.1
Allure Plugin version: 2.11
CLI: 1.5.0

**Comment by eroshenkoam** [comment]
@sheg, allure perfectly generate in concurrent builds. 
You have this error "Could not find any allure results" according to attached logs. 
Seems like you misconfigurate the path of allure results.
Can you check it?

**Comment by eroshenkoam** [comment]
Closed due not reponse

**Comment by pargev** [comment]
I use allure jenkins plugin. When I use the option "Execute concurrent builds if necessary" to run parallel the the report generates in

Report successfully generated to ~/.jenkins/workspace/Appium@4/allure-report or
Appium@3 , Appium@2 etc and nothing appear in report. Is there a way to combine
Appium@4 , Appium@3 etc folder reports into
~/.jenkins/workspace/Appium/allure-report
