### ISSUE TITLE
Invalid ALLURE_HOME on windows node.

### ISSUE THREAD

**Issue by F1ashhimself** [jenkinsci/allure-plugin#82]
## Issue
Strange issue, seems like "generate" command interprets `set "ALLURE_HOME=%~dp0.."` command incorrectly.

### Context
- **Jenkins version**: 2.32.2
- **Job type**: Matrix

- **Allure plugin version**: 2.13
- **Allure commandline version**: 1.5.2

### Logs & Traces
12:11:26 [win7] $ C:\jenkins\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\1.5.2\bin\allure.bat generate "C:\jenkins\workspace\my_job_name\MARK\my_mark\OS\win7\results\_allure" -o "C:\jenkins\workspace\my_job_name\MARK\my_mark\OS\win7\allure-report"
12:11:26 Invalid ALLURE_HOME: C:\jenkins\workspace\my_job_name\MARK\my_mark\OS\win7\.. is not a valid allure commandline directory 

NOTE: executing the same command from windows command line generates report successfully.

**Comment by eroshenkoam** [comment]
@F1ashhimself, can you build plugin from #84 and check it?

**Comment by F1ashhimself** [comment]
Still the same...

[allure-jenkins-plugin.zip](https://github.com/jenkinsci/allure-plugin/files/788052/allure-jenkins-plugin.zip)

**Comment by m3nthal** [comment]
It seems that `ALLURE_HOME` is not set correctly on plugin level.
I've added some lines in allure.bat file for debugging and replace the logic to always reset `ALLURE_HOME` and it worked!

```bat
@REM find and validate allure home directory
echo "Before: %ALLURE_HOME%"
set "ALLURE_HOME=%~dp0.."
echo "After: %ALLURE_HOME%"
if not exist "%ALLURE_HOME%\bin\allure.bat" (
    echo Invalid ALLURE_HOME: %ALLURE_HOME% is not a valid allure commandline directory >&2
    goto error
)
```

Jenkins log:
```
[TEST_JOB] $ C:\jenkins\qatools\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\default\bin\allure.bat generate "C:\jenkins\qatools\workspace\TEST_JOB\allure-results" -o "C:\jenkins\qatools\workspace\TEST_JOB\allure-report"
"Before: /C:\jenkins\qatools\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\default"
"After: C:\jenkins\qatools\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\default\bin\.."
16:44:26 Report successfully generated to the directory <C:\jenkins\qatools\workspace\TEST_JOB\allure-report>. Use `allure report open` command to show the report.
```

Notice `/` is added in front of the path before transformation. Could it be the issue?

**Comment by 1cto** [comment]
I've got the same trouble "/" in front of ALLURE_HOME. Any attepmpts to reassign the value of ALLURE_HOME on Jenkins level havn't been successful.

**Comment by F1ashhimself** [comment]
Still reproducible on matrix job

**Allure Jenkins Plugin 2.20**
**CLI 1.5.4**

`Invalid ALLURE_HOME: C:\jenkins\workspace\regression\MARK\tests1\OS\win7\.. is not a valid allure commandline directory
ERROR: Build step failed with exception
ru.yandex.qatools.allure.jenkins.exception.AllurePluginException: Can not generate Allure Report, exit code: 1
    at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:265)
    at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:186)
    at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:735)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:676)
    at hudson.model.Build$BuildExecution.post2(Build.java:186)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:621)
    at hudson.model.Run.execute(Run.java:1760)
    at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
    at hudson.model.ResourceController.execute(ResourceController.java:97)
    at hudson.model.Executor.run(Executor.java:405)`

**Comment by eroshenkoam** [comment]
@F1ashhimself we tested this issue all day long but no luck 
Can you install the latest version of plugin and try it one more time?

**Comment by F1ashhimself** [comment]
@eroshenkoam All is fine with latest plugin and cli. Thank you!
