### ISSUE TITLE
Please update https://wiki.jenkins-ci.org/display/JENKINS/Allure+Plugin

### ISSUE THREAD

**Issue by tarvitz** [jenkinsci/allure-plugin#83]
Hi, please update the following jenkins page because user have no even idea what exactly has been changed.

Much appreciate that.

**Comment by eroshenkoam** [comment]
Done: https://wiki.jenkins-ci.org/display/JENKINS/Allure+Plugin

**Comment by tarvitz** [comment]
Thank you, it was really nice to have :)
