### ISSUE TITLE
ru.yandex.qatools.allure.jenkins.execption.AllurePluginException: Can not generate Allure Report, exit code: 255

### ISSUE THREAD

**Issue by abidrana7** [jenkinsci/allure-plugin#86]
## Issue
ru.yandex.qatools.allure.jenkins.execption.AllurePluginException: Can not generate Allure Report, exit code: 255

### Context 
Trying to generate the allure reports by ALLURE COMMAND LINE but got error as the followings:
ru.yandex.qatools.allure.jenkins.execption.AllurePluginException: Can not generate Allure Report, exit code: 255

- **Jenkins version**: 2.32
- **Job type**: Freestyle

- **Allure plugin version**: 2.13
- **Allure commandline version**: 1.5.2

### Problem description

_Describe your problem in a meaningful way_:
- what were you doing: I'm  tryion to create Allure report once protractor-jasmine test is finished 
- what was expected: Allure reports should be created and embeded in PROJECT dashboard on Jenkins
- what occurred finally: Unable to get the desired results due the error as mentioned in below 'Logs & Traces' 

### Logs & Traces
[protracsol] $ "C:\Program Files (x86)\Jenkins\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\latest\bin\allure.bat" generate "D:\jenkins-workspace\workspace\protracsol\allure-results" -o "D:\jenkins-workspace\workspace\protracorsol\allure-report" \Jenkins\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\latest\bin.. was unexpected at this time. ERROR: Build step failed with exception ru.yandex.qatools.allure.jenkins.execption.AllurePluginException: Can not generate Allure Report, exit code: 255
_Please include any relevant log that could serve to better understand the source of your issue_
Once I downloaded the ALLURE Command line tools manually and extract it, it is found that **/bin/allure.bat** working fine on the hand once it is placed in **C:\Program Files (x86)\Jenkins\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\latest\bin\allure.bat** got the issue as mentioned above.

**Comment by abidrana7** [comment]
This issue appeared because of Jenkins, when I used its windows installer version so I faced this issue. Once I uninstall the jenkins windows installer and then installed again jenkins.war this issue was resolved.

**Comment by mkimbro** [comment]
I haven't looked at the code, but this seems to be related to the parenthesis in the path to the Allure Commandline Installation directory. Jenkins automatic installer (on Windows) drops the tool in C:\Program Files (x86)\Jenkins. If you create a local installation manually with parenthesis in the path, you can reproduce the same behavior.

**Comment by eroshenkoam** [comment]
@abidrana7 can you test this on 2.16?

**Comment by eroshenkoam** [comment]
seems like fixes in 2.17
