### ISSUE TITLE
There is mistake in package folder name execption

### ISSUE THREAD

**Issue by simple-elf** [jenkinsci/allure-plugin#93]
### Context
- **Jenkins version**: any
- **Job type**: any

- **Allure plugin version**: 2.14
- **Allure commandline version**: unknown

### Problem description

Packege folder name with Exception class has mistake [execption](https://github.com/jenkinsci/allure-plugin/tree/master/src/main/java/ru/yandex/qatools/allure/jenkins/execption)

Need to rename to "exception"

### Logs & Traces

None

**Comment by eroshenkoam** [comment]
ty
